import test from 'node:test';
import assert from 'node:assert/strict';
import {project,clone,newPage} from '../web/src/core.js';
import {VisionJobs} from '../web/src/vision.js';
function fixture(){const d=project('Saved candidate'),v=new VisionJobs(),c=v.sampleCandidate(d);d.candidates.push(c);return {d,v,c};}
test('saved candidate review after adoption uses original frame without changing edited adopted page',()=>{const {d,v,c}=fixture(),original=clone(d.pages[0]),adopted=v.adopt(d,c);adopted.elements[0].name='manual edit';const before=JSON.stringify(d),preview=v.preview(d,clone(c));assert.equal(preview.page.id,original.id);assert.deepEqual(preview.page.canvas,original.canvas);assert.deepEqual(preview.page.elements,c.elements);assert.equal(JSON.stringify(d),before);preview.page.view.scale=10;preview.page.elements[0].name='preview-only';assert.equal(JSON.stringify(d),before);assert.throws(()=>v.adopt(d,clone(c)));assert.equal(JSON.stringify(d),before);});
test('saved pending candidate review on another page never makes that page an adoption target',()=>{const {d,v,c}=fixture(),other=newPage('unrelated');d.pages.push(other);d.activePageId=other.id;const before=JSON.stringify(d);assert.equal(v.preview(d,clone(c)).page.id,c.sourceBinding.pageId);assert.throws(()=>v.adopt(d,clone(c)));assert.equal(JSON.stringify(d),before);});
for(const [label,mutate] of [['missing binding',c=>delete c.sourceBinding],['unknown frame',c=>c.coordinateSpace='unknown'],['mismatched image dimensions',c=>c.sourceWidth+=1]])test(`saved ${label} never gets guessed for review or adoption`,()=>{const {d,v,c}=fixture();mutate(c);const before=JSON.stringify(d);assert.throws(()=>v.preview(d,clone(c)));assert.throws(()=>v.adopt(d,clone(c)));assert.equal(JSON.stringify(d),before);});
test('saved candidate source page removal and duplicate binding pages remain rejected',()=>{for(const remove of [true,false]){const {d,v,c}=fixture(),other=newPage('other');d.pages.push(other);d.activePageId=other.id;if(remove)d.pages.shift();else d.pages.push(clone(d.pages[0]));const before=JSON.stringify(d);assert.throws(()=>v.preview(d,clone(c)));assert.equal(JSON.stringify(d),before);}});
test('source page replacement rejects stored preview even when active adopted page is intact',()=>{const {d,v,c}=fixture(),adopted=v.adopt(d,c);d.pages[0].sourceId='changed-source';const before=JSON.stringify(d);assert.throws(()=>v.preview(d,clone(c)));assert.throws(()=>v.adopt(d,clone(c)));assert.equal(d.activePageId,adopted.id);assert.equal(JSON.stringify(d),before);});
test('candidate payload changes cannot borrow saved candidate ownership from another active page',()=>{const {d,v,c}=fixture();v.adopt(d,c);const altered=clone(c);altered.elements[0].x+=1;const before=JSON.stringify(d);assert.throws(()=>v.preview(d,altered));assert.throws(()=>v.adopt(d,altered));assert.equal(JSON.stringify(d),before);});
