// Targeted 004 regression: changed incremental drawing/gestures only; PWA update test excluded.
import {createRequire} from 'node:module';import {spawn} from 'node:child_process';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const require=createRequire(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/runtime.js':import.meta.url),{chromium}=require('playwright');const server=spawn('python3',['serve.py','--port','4176']);server.stderr.on('data',()=>{});let browser,page;const originalSW=await fs.readFile('web/sw.js','utf8');const results=[],errors=[];const log=(name,detail={})=>{results.push({name,result:'PASS',...detail});console.log('PASS '+name);};const click=a=>page.locator(`button[data-action=${a}]`).first().click();
try{browser=await chromium.launch({executablePath:process.env.VDRAW_CHROMIUM||'/tmp/chromium',args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true});page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4176');await click('sample');await page.waitForFunction(()=>VDRAW.state.saveState==='saved');await page.locator('#stage').waitFor();await page.waitForTimeout(60);const before=await page.evaluate(()=>JSON.stringify(VDRAW.editor.doc.pages[0].elements));const box=await page.locator('#stage').boundingBox();const cdp=await context.newCDPSession(page),point=(x,y,id)=>({x,y,id});const cx=195,cy=box.y+box.height/2;
 if(!process.env.PWA_ONLY){
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[point(cx,cy,1)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[point(cx+40,cy+30,1)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await page.evaluate(()=>JSON.stringify(VDRAW.editor.doc.pages[0].elements)),before);assert.ok(await page.evaluate(()=>VDRAW.editor.doc.pages[0].view.x>20));log('実CDP一本指パンで図形が移動しない');
 await click('fit');await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[point(cx-30,cy,1),point(cx+30,cy,2)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[point(cx-65,cy,1),point(cx+65,cy,2)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(await page.evaluate(()=>VDRAW.editor.doc.pages[0].view.scale>2));assert.equal(await page.evaluate(()=>JSON.stringify(VDRAW.editor.doc.pages[0].elements)),before);log('実CDP二本指ズームで図形を保持');await click('fit');
 // Select a visually thin line by tapping 6 CSS px away: larger hit region.
 const pos=await page.evaluate(()=>{const m=document.querySelector('#scene-group').getScreenCTM();return{x:m.a*650+m.e,y:m.d*600+m.f+6};});await page.touchscreen.tap(pos.x,pos.y);await page.locator('[data-action=object]').filter({hasText:'配線ルート'}).click();await page.locator('#object-name').waitFor();log('細線から6CSSpx離れたタップで候補選択');await click('move');const old=await page.evaluate(()=>VDRAW.editor.doc.pages[0].elements[5].x);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[point(cx,cy,1)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[point(cx+35,cy+20,1)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.notEqual(await page.evaluate(()=>VDRAW.editor.doc.pages[0].elements[5].x),old);await click('undo');assert.equal(await page.evaluate(()=>JSON.stringify(VDRAW.editor.doc.pages[0].elements)),before);log('明示モードで一本指対象移動・Undo');

 }
 await page.evaluate(()=>document.querySelector('#toast').style.display='none');await page.screenshot({path:'evidence/02-editor-clean.png'});await click('back');await page.locator('#search').waitFor();await page.evaluate(()=>document.querySelector('#toast').style.display='none');await page.screenshot({path:'evidence/01-home-clean.png'});await click('open');await page.locator('#stage').waitFor();await click('export');await page.screenshot({path:'evidence/03-export-clean.png'});await click('edit');await click('back');await page.locator('#search').waitFor();await click('new');await page.screenshot({path:'evidence/input-clean.png'});await click('dismiss');await click('materials');await page.screenshot({path:'evidence/materials-clean.png'});await click('settings');await page.screenshot({path:'evidence/settings-clean.png'});
 assert.equal(errors.length,0);await fs.writeFile('evidence/gestures-004-results.json',JSON.stringify({results,errors,testMode:'Chromium CDP touch; no Android/iPhone device'},null,2));
}catch(e){console.error(e);if(page)await page.screenshot({path:'evidence/gestures-update-failure.png'});await fs.writeFile('evidence/gestures-004-results.json',JSON.stringify({results,errors,failure:e.stack},null,2));process.exitCode=1;}finally{await browser?.close();server.kill();}
