import test from 'node:test';import assert from 'node:assert/strict';
import {nativeRuntime} from '../web/src/native-runtime.js';
function fixture(fail=[]){const events={},calls=[],errors=[];const listener=scope=>({async addListener(name,fn){calls.push(name);if(fail.includes(name))throw Error('injected');events[name]=fn;return {async remove(){calls.push('remove:'+name);delete events[name];}};}});const plugins={App:{...listener('App'),async minimizeApp(){calls.push('minimize');}},StatusBar:{async setStyle(){calls.push('status');if(fail.includes('status'))throw Error('injected');}},Style:{Light:'LIGHT'},Keyboard:listener('Keyboard'),SplashScreen:{async hide(){calls.push('hide');if(fail.includes('splash'))throw Error('injected');}}};const handlers={async back(){calls.push('back');return false;},async suspend(){calls.push('suspend');return true;},async resume(){calls.push('resume');},async restoredPhoto(p){calls.push(p);},resize(){calls.push('resize');},error(e){errors.push(e);}};return{plugins,handlers,events,calls,errors};}
const tick=()=>new Promise(r=>setImmediate(r));
test('isolates status and keyboard failures; splash still hides',async()=>{const f=fixture(['status','keyboardDidShow']);const r=nativeRuntime(f.plugins,f.handlers);const health=await r.start();assert.equal(health.statusBar,'failed');assert.equal(health.keyboardDidShow,'failed');assert.equal(health.splash,'ready');assert.ok(f.events.backButton);assert.ok(f.events.appRestoredResult);assert.equal(f.errors.length,2);});
test('back consumed by editor does not minimize; unconsumed home back does',async()=>{const f=fixture();let consumed=true;f.handlers.back=async()=>consumed;const r=nativeRuntime(f.plugins,f.handlers);await r.start();f.events.backButton();await tick();assert.equal(f.calls.includes('minimize'),false);consumed=false;f.events.backButton();await tick();assert.equal(f.calls.filter(x=>x==='minimize').length,1);});
test('failed save prevents minimizing and reports error',async()=>{const f=fixture();f.handlers.back=async()=>{throw Error('save failed');};const r=nativeRuntime(f.plugins,f.handlers);await r.start();f.events.backButton();await tick();assert.ok(!f.calls.includes('minimize'));assert.match(f.errors[0],/save failed/);});
test('pause and resume are actual callbacks; failed pause is reported',async()=>{const f=fixture();f.handlers.suspend=async()=>false;const r=nativeRuntime(f.plugins,f.handlers);await r.start();f.events.appStateChange({isActive:false});await tick();assert.match(f.errors[0],/保存/);f.events.appStateChange({isActive:true});await tick();assert.ok(f.calls.includes('resume'));});
test('only successful Camera.getPhoto restored results imported; failed result reported',async()=>{const f=fixture();const r=nativeRuntime(f.plugins,f.handlers);await r.start();const p={webPath:'file://photo'};f.events.appRestoredResult({pluginId:'Other',methodName:'getPhoto',success:true,data:p});f.events.appRestoredResult({pluginId:'Camera',methodName:'pickImages',success:true,data:p});await tick();assert.ok(!f.calls.includes(p));f.events.appRestoredResult({pluginId:'Camera',methodName:'getPhoto',success:true,data:p});await tick();assert.ok(f.calls.includes(p));f.events.appRestoredResult({pluginId:'Camera',methodName:'getPhoto',success:false,error:{message:'denied'}});await tick();assert.match(f.errors[0],/denied/);});
test('listener cleanup suppresses old callbacks and removes each subscription',async()=>{const f=fixture();const r=nativeRuntime(f.plugins,f.handlers);await r.start();const old=f.events.backButton;await r.dispose();old();await tick();assert.ok(!f.calls.includes('minimize'));assert.equal(f.calls.filter(x=>typeof x==='string'&&x.startsWith('remove:')).length,5);});
test('splash failure visible; all other features remain ready',async()=>{const f=fixture(['splash']);const r=nativeRuntime(f.plugins,f.handlers);const h=await r.start();assert.equal(h.splash,'failed');assert.equal(h.back,'ready');assert.match(f.errors[0],/splash/);});
