import {createRequire} from 'node:module';import {spawn} from 'node:child_process';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const require=createRequire(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/runtime.js':import.meta.url),{chromium}=require('playwright');const server=spawn('python3',['serve.py','--port','4175']);server.stderr.on('data',()=>{});let browser;const measurements=[],errors=[];
try{browser=await chromium.launch({executablePath:process.env.VDRAW_CHROMIUM||'/tmp/chromium',args:['--no-sandbox','--enable-precise-memory-info']});const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4175');await page.locator('[data-action=sample]').waitFor();
 const cdp=await context.newCDPSession(page);
 for(const cpuRate of [1,4]){await cdp.send('Emulation.setCPUThrottlingRate',{rate:cpuRate});
 for(let repeat=1;repeat<=3;repeat++)for(const count of [500,2000,5000]){await cdp.send('HeapProfiler.collectGarbage');
  const m=await page.evaluate(async count=>{const {project,element}=await import('./src/core.js');const d=project('性能試験 '+count+'要素');d.sample=true;for(let i=0;i<count;i++)d.pages[0].elements.push(element(i%9===0?'line':'rect','合成対象'+i,{x:20+i%100*11,y:20+Math.floor(i/100)*14,w:8,h:i%9===0?0:9,fill:i%9===0?'none':'#BACFC7',strokeWidth:1}));const t=performance.now();VDRAW.begin(d);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return {count,id:d.id,initialRenderMs:performance.now()-t,heapBefore:performance.memory?.usedJSHeapSize};},count);
  m.cpuRate=cpuRate;m.repeat=repeat;
  const box=await page.locator('#stage').boundingBox(),before=await page.evaluate(()=>JSON.stringify(VDRAW.editor.doc.pages[0].elements));
  await page.evaluate(()=>{window.panFrames=[];window.panActive=true;window.panNode=document.querySelector('#scene-group').firstChild;let last=performance.now();function tick(){const t=performance.now();window.panFrames.push(t-last);last=t;if(window.panActive)requestAnimationFrame(tick);}requestAnimationFrame(tick);});
  const tpan=Date.now();await page.mouse.move(box.x+130,box.y+150);await page.mouse.down();await page.mouse.move(box.x+180,box.y+180,{steps:20});await page.mouse.up();m.realMousePanMs=Date.now()-tpan;m.pan=await page.evaluate(()=>{window.panActive=false;const frames=window.panFrames.slice(1).sort((a,b)=>a-b);return {frameP95Ms:frames[Math.floor(frames.length*.95)],sameNode:window.panNode===document.querySelector('#scene-group').firstChild};});assert.ok(m.pan.sameNode);
  assert.equal(await page.evaluate(()=>JSON.stringify(VDRAW.editor.doc.pages[0].elements)),before);
  const z=await page.evaluate(async()=>{const st=document.querySelector('#stage'),r=st.getBoundingClientRect(),node=document.querySelector('#scene-group').firstChild,frames=[],t=performance.now();for(let i=0;i<12;i++){const a=performance.now();st.dispatchEvent(new WheelEvent('wheel',{deltaY:-1,clientX:r.x+180,clientY:r.y+200,bubbles:true,cancelable:true}));await new Promise(requestAnimationFrame);frames.push(performance.now()-a);}return {durationMs:performance.now()-t,frameP95Ms:frames.sort((a,b)=>a-b)[Math.floor(frames.length*.95)],sameNode:node===document.querySelector('#scene-group').firstChild};});m.zoom=z;assert.ok(z.sameNode);
  await page.locator('[data-action=fit]').click();await page.waitForTimeout(50);const position=await page.evaluate(()=>{const m=document.querySelector('#scene-group').getScreenCTM();return {x:m.a*26+m.e,y:m.d*24+m.f};});const ts=Date.now();await page.touchscreen.tap(position.x,position.y);await page.locator('.sheet').waitFor();if(await page.locator('[data-action=object]').count())await page.locator('[data-action=object]').first().click();await page.locator('#object-color').waitFor();m.touchSelectionAndPanelMs=Date.now()-ts;
  const tc=Date.now();await page.locator('#object-color').fill('#AA4422');await page.locator('[data-action=apply-object]').click();await page.locator('#object-color').waitFor({state:'hidden'});m.colorChangeUiMs=Date.now()-tc;assert.ok(await page.evaluate(()=>VDRAW.editor.doc.pages[0].elements.some(e=>e.fill.toLowerCase()==='#aa4422'||e.stroke.toLowerCase()==='#aa4422')));
  m.saveMs=await page.evaluate(async()=>{const t=performance.now();if(!await VDRAW.save(true))throw Error('保存失敗：'+document.querySelector('#toast').textContent);return performance.now()-t;});const saved=await page.evaluate(()=>JSON.stringify(VDRAW.editor.doc.pages[0].elements));const tr=Date.now();await page.reload();await page.locator(`[data-action=open][data-id="${m.id}"]`).first().click();await page.locator('#stage').waitFor();await page.waitForTimeout(40);m.reloadAndResumeMs=Date.now()-tr;assert.equal(await page.evaluate(()=>JSON.stringify(VDRAW.editor.doc.pages[0].elements)),saved);
  const memory=await page.evaluate(async()=>{const t=performance.now(),id=VDRAW.editor.doc.pages[0].elements[0].id;for(let i=0;i<30;i++)VDRAW.editor.update(id,{name:'修正'+i});return {thirtyCommandsMs:performance.now()-t,undoSnapshots:VDRAW.editor.undoStack.length,heapAfter:performance.memory?.usedJSHeapSize};});Object.assign(m,memory);await cdp.send('HeapProfiler.collectGarbage');m.heapAfterGC=await page.evaluate(()=>performance.memory?.usedJSHeapSize);assert.ok(memory.undoSnapshots<=40000/count);m.errors=[...errors];m.status='MEASURED';measurements.push(m);console.log(JSON.stringify(m));await fs.writeFile('evidence/performance-003-results.json',JSON.stringify({environment:'Container Chromium 390x844; CDP CPU throttle 1x / 4x, 3 repetitions. Synthetic elements. Not Android/iPhone. Pan mouse events, selection touch tap, zoom WheelEvent.',measurements,errors},null,2));
 }
 }
 assert.equal(errors.length,0);
}catch(e){console.error(e);await fs.writeFile('evidence/performance-003-results.json',JSON.stringify({measurements,errors,failure:e.stack},null,2));process.exitCode=1;}finally{await browser?.close();server.kill();}
