// Inherited 002 test; not run in phase 003. See docs/TEST-PROCEDURE.md.
import {createRequire} from 'node:module';import {spawn} from 'node:child_process';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const require=createRequire(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/runtime.js':import.meta.url),{chromium}=require('playwright');const results=[],errors=[],consoleErrors=[];let browser,server,page,context;
const log=(name,detail={})=>{results.push({name,result:'PASS',...detail});console.log('PASS '+name);};
const click=async action=>{await page.locator(`button[data-action="${action}"]`).first().click();if(action==="open")await page.locator("#stage").waitFor();if(action==="back")await page.locator("#search").waitFor();if(action==="blank")await page.waitForFunction(()=>VDRAW.state.screen==="edit"&&VDRAW.editor?.doc.title==="名称未設定の現調");};
const saved=()=>page.waitForFunction(()=>window.VDRAW.state.saveState==='saved');
const current=()=>page.evaluate(()=>structuredClone(window.VDRAW.editor.doc));
const content=d=>d.pages.map(p=>({id:p.id,name:p.name,elements:p.elements}));
const attach=p=>{p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});};
try{
 server=spawn('python3',['serve.py','--port','4173']);server.stderr.on('data',()=>{});
 browser=await chromium.launch({headless:true,executablePath:process.env.VDRAW_CHROMIUM||'/tmp/chromium',args:['--no-sandbox']});context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,acceptDownloads:true});page=await context.newPage();attach(page);
 await page.goto('http://127.0.0.1:4173');await page.locator('[data-action=new]').waitFor();log('002起動');
 await page.evaluate(()=>localStorage.setItem('legacy-preservation-sentinel','UNCHANGED'));await click('sample');await saved();await page.locator('#stage').waitFor();
 if(process.env.PRODUCT_PHASE!=='remaining'){
 await click('back');await page.screenshot({path:'evidence/01-home.png'});await click('open');
 const layouts=[];for(const [width,height] of [[320,740],[360,800],[375,812],[390,844],[430,932],[844,390],[1440,900]]){
  await page.setViewportSize({width,height});await page.waitForTimeout(80);const l=await page.evaluate(()=>{const r=document.querySelector('.canvas-wrap').getBoundingClientRect(),bs=[...document.querySelectorAll('button')].filter(b=>b.offsetWidth);return {scroll:document.body.scrollHeight,overflow:document.body.scrollWidth>innerWidth,canvasRatio:r.height/innerHeight,minW:Math.min(...bs.map(b=>b.getBoundingClientRect().width)),minH:Math.min(...bs.map(b=>b.getBoundingClientRect().height))};});assert.equal(l.overflow,false);assert.ok(l.scroll<=height+1);assert.ok(l.minW>=48&&l.minH>=48);layouts.push({width,height,...l});await page.screenshot({path:`evidence/editor-${width}x${height}.png`});
 }log('320/360/375/390/430・横画面・PC、スクロール不要と48px領域',{layouts});
 await page.setViewportSize({width:390,height:844});await click('select');await page.locator('[data-action=object]').filter({hasText:'ソファ'}).click();await page.locator('#object-color').fill('#AA4422');await page.locator('#object-width').fill('7');await click('apply-object');await saved();assert.equal((await current()).pages[0].elements[2].strokeWidth,7);log('実色・線幅の変更を700ms自動保存');
 const stored=await current();await page.close();page=await context.newPage();attach(page);await page.goto('http://127.0.0.1:4173');await click('open');assert.deepEqual(content(await current()),content(stored));await click('undo');assert.equal((await current()).pages[0].elements[2].fill,'#BACFC7');await click('redo');assert.equal((await current()).pages[0].elements[2].fill,'#aa4422');await saved();log('タブ閉鎖→案件再開、保存済みUndo/Redo復元');
 await click('select');await page.locator('[data-action=object]').filter({hasText:'ソファ'}).click();await page.screenshot({path:'evidence/object-panel.png'});await click('delete-object');assert.equal((await current()).pages[0].elements.length,6);await click('undo');assert.equal((await current()).pages[0].elements.length,7);await click('redo');await click('undo');log('対象削除・Undo/Redo');
 await click('add');await page.locator('[data-action=insert][data-kind=arc]').click();await page.locator('#object-name').fill('扉の円弧');await click('apply-object');await saved();assert.equal((await current()).pages[0].elements.at(-1).kind,'arc');log('編集可能な円弧を追加');
 await click('pages');await click('add-page');await click('add');await page.locator('[data-action=insert][data-kind=text]').click();await page.locator('#object-text').fill('第2ページの確認');await click('apply-object');await saved();assert.equal((await current()).pages.length,2);log('複数ページ追加・文字編集・保存');

 }else{await page.evaluate(async()=>{const {sample,element,newPage}=await import('./src/core.js');const d=sample();d.pages[0].elements.push(element('arc','扉の円弧',{w:160,h:160,startAngle:0,endAngle:180,fill:'none'}));const p=newPage('図面 2');p.elements.push(element('text','確認',{text:'第2ページの確認'}));d.pages.push(p);VDRAW.begin(d);await VDRAW.save(true);});log('保存済み前半試験は再実行せず、残工程用の合成fixtureで再開');}
 await click('back');await click('new');const event=page.waitForEvent('filechooser');await click('photo');await event;await click('dismiss');await click('new');await click('blank');await click('save');await saved();const second=(await current()).id;await click('back');assert.ok(await page.locator('[data-action=open]').count()>=3);await page.screenshot({path:'evidence/01-home-multiple.png'});await page.locator('[data-action=open]').filter({hasText:'室内レイアウト'}).first().click();await page.waitForFunction(id=>VDRAW.editor?.doc.id!==id,second);assert.notEqual((await current()).id,second);log('新規→写真選択2操作・複数案件・選んだ案件再開');
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await context.setOffline(true);await page.reload();await page.locator('[data-action=open]').first().waitFor();await page.locator('[data-action=open]').filter({hasText:'室内レイアウト'}).first().click();await click('select');await page.locator('[data-action=object]').first().click();await page.locator('#object-name').fill('オフライン編集');await click('apply-object');await saved();await context.setOffline(false);log('通信断でshell起動・既存案件の編集・自動保存');
 await page.evaluate(()=>{window.goodSave=VDRAW.store.save;VDRAW.store.save=async()=>{throw new DOMException('試験注入','QuotaExceededError');};});await click('add');await page.locator('[data-action=insert][data-kind=line]').click();await click('apply-object');await page.waitForFunction(()=>VDRAW.state.saveState==='failed');assert.match(await page.locator('.editor-header .status').textContent(),/保存失敗/);await page.evaluate(()=>VDRAW.store.save=window.goodSave);await click('save');await saved();log('容量不足注入→保存失敗表示→再試行成功');
 await click('select');await page.locator('[data-action=object]').first().click();await page.setViewportSize({width:390,height:430});const rect=await page.locator('[data-action=apply-object]').boundingBox();assert.ok(rect.y+rect.height<=430);await page.screenshot({path:'evidence/keyboard-height-simulation.png'});await click('dismiss');await page.setViewportSize({width:320,height:740});await page.evaluate(()=>document.documentElement.classList.add('large-type'));await click('select');await page.locator('[data-action=object]').first().click();const b=await page.locator('[data-action=apply-object]').boundingBox();assert.ok(b.x>=0&&b.x+b.width<=320&&b.y+b.height<=740);await page.screenshot({path:'evidence/large-text-320.png'});await click('dismiss');await page.evaluate(()=>document.documentElement.classList.remove('large-type'));await page.setViewportSize({width:390,height:844});log('文字拡大320px・キーボード相当高さ430pxで確定ボタン可視',{actualKeyboard:false});
 await click('pages');await page.locator('[data-action=page]').first().click();await saved();await page.screenshot({path:'evidence/02-editor.png'});
 await click('export');await page.screenshot({path:'evidence/03-export.png'});const files=[];for(const format of ['pptx','dxf','pdf','xlsx','json','png','svg']){await page.locator(`[data-action=format][data-format=${format}]`).click();const event=page.waitForEvent('download');await click('download');const download=await event;const path=`evidence/ui-output.${format}`;await download.saveAs(path);await saved();const stat=await fs.stat(path);assert.ok(stat.size>100);files.push({format,bytes:stat.size});}log('7形式をUIから実ファイル生成・存在・サイズ確認',{files});
 const cdp=await context.newCDPSession(page);const installation=await cdp.send('Page.getInstallabilityErrors');await fs.writeFile('evidence/pwa-installability.json',JSON.stringify(installation,null,2));assert.equal(installation.installabilityErrors.length,0);log('Chromium PWAインストール条件検査',{installation});
 await click('edit');await saved();const corruptId=(await current()).id;
 await page.evaluate(async id=>{await VDRAW.store.transaction('readwrite',s=>{const r=s.get(id);r.onsuccess=()=>{const record=r.result;record.payload.doc.title='不正に変更';s.put(record);};});},corruptId);const corruptBefore=await page.evaluate(id=>VDRAW.store.transaction('readonly',s=>s.get(id)),corruptId);
 const blocked=await page.evaluate(async()=>{try{await VDRAW.store.save(VDRAW.editor.doc);return false;}catch(e){return e.message;}});assert.match(blocked,/整合性/);await page.reload();await page.locator('[data-action=recover]').waitFor();await click('recover');await saved();assert.notEqual((await current()).id,corruptId);const corruptAfter=await page.evaluate(id=>VDRAW.store.transaction('readonly',s=>s.get(id)),corruptId);assert.deepEqual(corruptAfter,corruptBefore);log('破損案件の安全停止・原記録保全・直前保存を別案件へ復旧');
 await click('save');await saved();let conflict=await page.evaluate(async()=>{const {LocalStore}=await import('./src/storage.js');const a=new LocalStore(),b=new LocalStore(),d=structuredClone(VDRAW.editor.doc);const writes=await Promise.allSettled([a.save({...d,title:'画面A'}),b.save({...d,title:'画面B'})]);return writes.map(r=>({status:r.status,message:r.reason?.message}));});assert.ok(conflict.some(r=>r.status==='rejected'));log('別画面の同時保存競合を検知',{conflict});
 assert.equal(await page.evaluate(()=>localStorage.getItem('legacy-preservation-sentinel')),'UNCHANGED');assert.equal(errors.length,0);assert.equal(consoleErrors.length,0);log('既存localStorage非変更・Console Error 0');
 await fs.writeFile('evidence/product-results.json',JSON.stringify({results,errors,consoleErrors,actualDevices:0,realAI:0},null,2));
}catch(e){console.error(e);if(page)await page.screenshot({path:'evidence/product-failure.png'});await fs.writeFile('evidence/product-results.json',JSON.stringify({results,errors,consoleErrors,failure:e.stack},null,2));process.exitCode=1;}finally{await browser?.close();server?.kill();}
