// Independent QA v2: invalid raw arcs may be rejected as [] or by exception.
// Original v1 evidence and 31 test cases are retained; normal arc requirements stay strict.
// No browser/device claims: OS handoff is explicitly mocked; arc hangs are process-bounded.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {spawnSync} from 'node:child_process';
import vm from 'node:vm';
import {deflateSync} from 'node:zlib';
const root=path.resolve(process.env.QA_TARGET_ROOT||new URL('..',import.meta.url).pathname);
const load=rel=>import(pathToFileURL(path.join(root,rel)).href);
const core=await load('web/src/core.js'),{VisionJobs}=await load('web/src/vision.js'),render=await load('web/src/render.js');
const appText=fs.readFileSync(path.join(root,'web/src/app.js'),'utf8');
const functionText=(name,next)=>appText.slice(appText.indexOf(`function ${name}(`),appText.indexOf(`\nfunction ${next}(`,appText.indexOf(`function ${name}(`)));
function boundedArc(start,end,{raw=false}={}){
 const code=`import {project,element,arcPoints,validate} from './web/src/core.js'; import {importFile} from './web/src/importers.js'; import {drawingSvg,shape,selection,hit} from './web/src/render.js'; const e=element('arc','QA',{w:160,h:160,startAngle:${start},endAngle:${end}}); try { ${raw?'let pts;try{pts=arcPoints(e);}catch(e){console.log("REJECTED");process.exit(0);}if(!Array.isArray(pts)||pts.length!==0)throw Error("invalid raw arc was not safely rejected");const rendered=shape(e),selectionSvg=selection(e);if(/NaN|Infinity|undefined/.test(rendered+selectionSvg))throw Error("nonfinite SVG");if(rendered!==""&&!rendered.includes("points="+String.fromCharCode(34,34)))throw Error("invalid arc still drawable");if(hit(e,e.x+e.w/2,e.y+e.h/2,15)!==false)throw Error("invalid arc still selectable");console.log("REJECTED_EMPTY SHAPE_SELECTION_HIT_SAFE");':'const d=project("QA external backup");d.pages[0].elements.push(e);const json=JSON.stringify(d);let accepted;try{accepted=await importFile({name:"qa.json",size:json.length,text:async()=>json});}catch(e){console.log("REJECTED");process.exit(0);}console.log("ACCEPTED");const pts=arcPoints(accepted.pages[0].elements[0]);if(pts.length!==49||!pts.flat().every(Number.isFinite))throw Error("nonfinite result");drawingSvg(accepted.pages[0]);console.log("FINITE");'} }catch(e){console.error(e.message);process.exitCode=1;}`;
 return spawnSync(process.execPath,['--input-type=module','-e',code],{cwd:root,timeout:700,encoding:'utf8',maxBuffer:4096});
}
for(const [name,start,end] of [['original huge angle','1e308','0'],['large finite non-progress angle','1e20','0']])test(`ENGINE external JSON ${name} terminates safely`,()=>{const r=boundedArc(start,end);assert.equal(r.error?.code,undefined,`renderer hung: ${r.stdout}`);assert.equal(r.status,0,r.stderr);assert.match(r.stdout,/FINITE|REJECTED/);});
for(const [name,start,end] of [['Infinity','Infinity','0'],['negative Infinity','0','-Infinity'],['NaN','NaN','0'],['raw huge finite','1e308','0'],['raw large finite','1e20','0']])test(`ENGINE raw bypass ${name} terminates or rejects`,()=>{const r=boundedArc(start,end,{raw:true});assert.equal(r.error?.code,undefined,'raw renderer hung');assert.equal(r.status,0,r.stderr);assert.match(r.stdout,/FINITE|REJECTED/);});
for(const [start,end] of [[0,180],[0,720],[720,0],[180,0]])test(`ENGINE normal/multiturn ${start}→${end} yields 49 finite bounded points`,()=>{const e=core.element('arc','normal',{w:160,h:160,startAngle:start,endAngle:end});const d=core.project('normal');d.pages[0].elements=[e];core.validate(d);const pts=core.arcPoints(e);assert.equal(pts.length,49);assert.ok(pts.flat().every(Number.isFinite));assert.ok(pts.every(([x,y])=>x>=e.x-1e-6&&x<=e.x+e.w+1e-6&&y>=e.y-1e-6&&y<=e.y+e.h+1e-6));assert.ok(render.shape(e).includes('<polyline'),'normal arc cannot be omitted');assert.ok(!render.shape(e).includes('points=""'),'normal arc points cannot be omitted');assert.ok(!/NaN|Infinity/.test(render.shape(e)+render.selection(e)));assert.equal(render.hit(e,pts[0][0],pts[0][1],0.1),true);});
function crc(b){let c=0xffffffff;for(const x of b){c^=x;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function png(w,h,gray=0){const chunk=(type,data)=>{const t=Buffer.from(type),n=Buffer.alloc(4),sum=Buffer.alloc(4);n.writeUInt32BE(data.length);sum.writeUInt32BE(crc(Buffer.concat([t,data])));return Buffer.concat([n,t,data,sum]);};const ih=Buffer.alloc(13);ih.writeUInt32BE(w,0);ih.writeUInt32BE(h,4);ih[8]=8;ih[9]=0;const data=Buffer.alloc((w+1)*h,gray);for(let y=0;y<h;y++)data[y*(w+1)]=0;return'data:image/png;base64,'+Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',ih),chunk('IDAT',deflateSync(data)),chunk('IEND',Buffer.alloc(0))]).toString('base64');}
const image2000=png(2000,1000),differentImage2000=png(2000,1000,30);
function candidateFixture(){const d=core.project('wide image');d.pages[0].canvas={width:2000,height:1000,yAxis:'down'};d.pages[0].sourceId='s1';d.sources=[{id:'s1',kind:'photo',workImage:image2000,pageNumber:1}];const result={schema:'vdraw-vision-result/1',executionKind:'protocol-fixture',record:{status:'CANDIDATE_READY'},candidate:{sourceId:'s1',coordinateSpace:'drawing-1200x800',calibration:'UNSCALED',elements:[core.element('rect','centered',{x:600,y:400,w:120,h:80})]}};const vision=new VisionJobs(),candidate=vision.receive(d,result);return{d,result,vision,candidate};}
function actualPreviewSvg(f){const ctx=vm.createContext({candidate:f.candidate,vision:f.vision,p:()=>core.pageOf(f.d),doc:()=>f.d,src:()=>f.d.sources.find(s=>s.id===core.pageOf(f.d).sourceId),drawingSvg:render.drawingSvg,reviewTarget:null,selection:render.selection});vm.runInContext(functionText('candidatePreview','candidateSheet'),ctx);return vm.runInContext("candidatePreview('overlay')",ctx);}
function assertRejectWithoutMutation(f,mutate){mutate(f.d);const before=JSON.stringify(f.d);assert.throws(()=>actualPreviewSvg(f),'changed frame preview must reject');assert.throws(()=>f.vision.adopt(f.d,f.candidate),'changed frame adoption must reject');assert.equal(JSON.stringify(f.d),before,'reject must not change document');}
test('INPUT original 2000x1000 source: actual preview and adoption preserve normalized geometry',()=>{const f=candidateFixture(),svg=actualPreviewSvg(f),match=svg.match(/viewBox="0 0 ([\d.]+) ([\d.]+)"/);assert.ok(match,'real preview SVG frame');const pg=f.vision.adopt(f.d,f.candidate),e=pg.elements[0];assert.equal(f.candidate.elements[0].x/Number(match[1]),e.x/pg.canvas.width);assert.equal(f.candidate.elements[0].y/Number(match[2]),e.y/pg.canvas.height);});
test('INPUT receive preserves authoritative coordinateSpace and reference frame across JSON persistence',()=>{const f=candidateFixture();assert.equal(f.candidate.coordinateSpace,'drawing-1200x800');f.d.candidates.push(f.candidate);const persisted=JSON.parse(JSON.stringify(f.d)),saved=persisted.candidates[0],freshVision=new VisionJobs();const ff={d:persisted,candidate:saved,vision:freshVision};const svg=actualPreviewSvg(ff);assert.ok(svg.includes('viewBox="0 0 1200 800"'));const pg=freshVision.adopt(persisted,saved);assert.equal(pg.elements[0].x,600);assert.equal(pg.elements[0].y,400);});
test('INPUT source switch rejects preview/adoption atomically',()=>assertRejectWithoutMutation(candidateFixture(),d=>{d.sources.push({...d.sources[0],id:'s2'});d.pages[0].sourceId='s2';}));
test('INPUT same source on different active page rejects preview/adoption atomically',()=>assertRejectWithoutMutation(candidateFixture(),d=>{const p=core.newPage('other');p.sourceId='s1';p.canvas={width:2000,height:1000,yAxis:'down'};d.pages.push(p);d.activePageId=p.id;}));
test('INPUT same-size replacement image rejects stale candidate atomically',()=>assertRejectWithoutMutation(candidateFixture(),d=>{d.sources[0].workImage=differentImage2000;}));
test('INPUT source image pageNumber change rejects stale candidate atomically',()=>assertRejectWithoutMutation(candidateFixture(),d=>{d.sources[0].pageNumber=2;}));
test('INPUT unknown coordinateSpace is rejected before candidate acceptance',()=>{const f=candidateFixture();f.result.candidate.coordinateSpace='image-we-do-not-understand';assert.throws(()=>new VisionJobs().receive(f.d,f.result));});
// Output assertions are appended below; only boundary mocks, production function unchanged.
const mime={pptx:'application/vnd.openxmlformats-officedocument.presentationml.presentation',dxf:'application/dxf',pdf:'application/pdf'};
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};
let ExportJobs=null;const jobsPath=path.join(root,'web/src/export-jobs.js');if(fs.existsSync(jobsPath))({ExportJobs}=await import(pathToFileURL(jobsPath).href));
function outputFixture(f='pptx',{deferShare=false,deferSave=false}={}){
 const a=core.project('案件A'),b=core.project('案件B');a.pages[0].elements=[core.element('text','unchanged',{text:'before'})];a.revision=3;b.revision=19;
 const gen=deferred(),handoff=deferred(),saved=deferred(),calls=[],notices=[];const ownerA={doc:a},ownerB={doc:b};
 const ctx=vm.createContext({busy:false,format:f,includePhoto:false,includeOriginal:false,editor:ownerA,screen:'export',exportJobs:ExportJobs?new ExportJobs():undefined,clone:structuredClone,doc:()=>ctx.editor.doc,exportBusy:value=>calls.push({stage:'busy',value}),toast:text=>notices.push({owner:ctx.editor.doc.id,text}),measuredExport:(doc,format,options)=>{calls.push({stage:'generate',doc:structuredClone(doc),format,options:structuredClone(options)});return gen.promise;},downloadOrShare:async(blob,name,share)=>{calls.push({stage:'handoff',name,type:blob.type,share});return deferShare?handoff.promise:'downloaded';},uid:()=>crypto.randomUUID(),Date,markDirty:()=>calls.push({stage:'dirty',owner:ctx.editor.doc.id}),save:async()=>{calls.push({stage:'save',owner:ctx.editor.doc.id});return deferSave?saved.promise:true;},exportScreen:()=>calls.push({stage:'render-export',owner:ctx.editor.doc.id}),safeNotice:x=>x});
 const start=appText.indexOf('async function output(share)'),stop=appText.indexOf('\nfunction materials',start);assert.ok(start>=0&&stop>start);vm.runInContext(appText.slice(start,stop),ctx);
 return{a,b,ownerA,ownerB,ctx,gen,handoff,saved,calls,notices,start:share=>vm.runInContext(`output(${!!share})`,ctx),resolve:()=>gen.resolve(new Blob(['fixture '+f],{type:mime[f]}))};
}
const tick=()=>new Promise(r=>setImmediate(r));
for(const f of ['pptx','dxf','pdf'])test(`OUTPUT ${f}: format/options changes cannot relabel bytes or history`,async()=>{const x=outputFixture(f),pending=x.start(false);x.ctx.format=f==='pdf'?'dxf':'pdf';x.ctx.includePhoto=true;x.ctx.includeOriginal=true;x.resolve();await pending;const delivery=x.calls.find(c=>c.stage==='handoff');assert.ok(delivery);assert.equal(delivery.name,'案件A.'+f);assert.equal(delivery.type,mime[f]);assert.equal(x.a.exports.length,1);assert.equal(x.a.exports[0].format,f);assert.equal(x.a.exports[0].includePhoto,false);assert.equal(x.a.exports[0].includeOriginal,false);assert.equal(x.a.exports[0].revision,3);assert.equal(x.a.revision,4);});
test('OUTPUT deferred A→B cannot deliver under B name or touch B history',async()=>{const x=outputFixture(),beforeB=JSON.stringify(x.b),pending=x.start(false);x.ctx.editor=x.ownerB;x.resolve();await pending;assert.equal(x.calls.filter(c=>c.stage==='handoff').length,0);assert.equal(JSON.stringify(x.b),beforeB);assert.equal(x.a.exports.length,0);assert.ok(!x.notices.some(n=>n.owner===x.b.id&&/端末に保存しました|共有しました/.test(n.text)));});
test('OUTPUT deferred A→B→A new session cannot resurrect stale generation',async()=>{const x=outputFixture(),pending=x.start(false);x.ctx.editor=x.ownerB;x.ctx.editor={doc:x.a};x.resolve();await pending;assert.equal(x.calls.filter(c=>c.stage==='handoff').length,0);assert.equal(x.a.exports.length,0);});
test('OUTPUT edit during generation keeps newest geometry and cancels stale snapshot',async()=>{const x=outputFixture(),pending=x.start(false);x.a.pages[0].elements[0].text='NEW EDIT';x.a.revision++;x.resolve();await pending;assert.equal(x.a.pages[0].elements[0].text,'NEW EDIT');assert.equal(x.a.revision,4);assert.equal(x.a.exports.length,0);assert.equal(x.calls.filter(c=>c.stage==='handoff').length,0);});
test('OUTPUT direct metadata mutation without revision still invalidates stale job',async()=>{const x=outputFixture(),pending=x.start(false);x.a.title='Renamed after snapshot';x.resolve();await pending;assert.equal(x.a.title,'Renamed after snapshot');assert.equal(x.a.revision,3);assert.equal(x.a.exports.length,0);assert.equal(x.calls.filter(c=>c.stage==='handoff').length,0);});
test('OUTPUT owner changes after OS handoff: no history on B and no old A restoration',async()=>{const x=outputFixture('pdf',{deferShare:true}),pending=x.start(true);x.resolve();await tick();assert.equal(x.calls.filter(c=>c.stage==='handoff').length,1);const beforeB=JSON.stringify(x.b);x.ctx.editor=x.ownerB;x.handoff.resolve('share-requested');await pending;assert.equal(JSON.stringify(x.b),beforeB);assert.equal(x.a.exports.length,0);assert.equal(x.ctx.editor,x.ownerB);assert.ok(!x.calls.some(c=>c.stage==='save'&&c.owner===x.b.id));});
test('OUTPUT owner changes during save: stale success cannot overwrite B screen or notify as B success',async()=>{const x=outputFixture('dxf',{deferSave:true}),pending=x.start(false);x.resolve();await tick();assert.ok(x.calls.some(c=>c.stage==='save'));x.ctx.editor=x.ownerB;x.saved.resolve(true);await pending;assert.equal(x.b.exports.length,0);assert.equal(x.b.revision,19);assert.ok(!x.calls.some(c=>c.stage==='render-export'&&c.owner===x.b.id));assert.ok(!x.notices.some(n=>n.owner===x.b.id&&/端末に保存しました|共有しました|ダウンロードを開始しました/.test(n.text)));});
test('OUTPUT repeated concurrent clicks launch only one generation and one history',async()=>{const x=outputFixture(),first=x.start(false),second=x.start(true),third=x.start(false);assert.equal(x.calls.filter(c=>c.stage==='generate').length,1);x.resolve();await Promise.all([first,second,third]);assert.equal(x.calls.filter(c=>c.stage==='handoff').length,1);assert.equal(x.a.exports.length,1);assert.equal(x.ctx.busy,false);});
test('OUTPUT failed generation releases busy gate for a later job',async()=>{const x=outputFixture(),first=x.start(false);x.gen.reject(Error('controlled failure'));await first;assert.equal(x.ctx.busy,false);const next=deferred();x.ctx.measuredExport=(doc,format)=>{x.calls.push({stage:'second-generate',format});return next.promise;};const second=x.start(false);next.resolve(new Blob(['next'],{type:mime.pptx}));await second;assert.equal(x.calls.filter(c=>c.stage==='second-generate').length,1);assert.equal(x.a.exports.length,1);});
test('OUTPUT wrong MIME is rejected before delivery/history',async()=>{const x=outputFixture('pdf'),pending=x.start(false);x.gen.resolve(new Blob(['not pdf'],{type:'application/dxf'}));await pending;assert.equal(x.calls.filter(c=>c.stage==='handoff').length,0);assert.equal(x.a.exports.length,0);assert.equal(x.ctx.busy,false);});
test('OUTPUT attempted out-of-order B job cannot overlap A; later B job keeps B identity',async()=>{const x=outputFixture(),first=x.start(false);x.ctx.editor=x.ownerB;const attempted=x.start(false);await attempted;assert.equal(x.calls.filter(c=>c.stage==='generate').length,1,'parallel B launch must be serialized');x.resolve();await first;assert.equal(x.b.exports.length,0,'cancelled A must not deposit an entry in B');const bGeneration=deferred();x.ctx.measuredExport=(doc,f,options)=>{x.calls.push({stage:'later-generate',owner:doc.id,format:f});return bGeneration.promise;};const later=x.start(false);bGeneration.resolve(new Blob(['B bytes'],{type:mime.pptx}));await later;assert.equal(x.b.exports.length,1);assert.ok(x.calls.some(c=>c.stage==='handoff'&&c.name==='案件B.pptx'));assert.equal(x.a.exports.length,0);});
