import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import {status,configuration,runVision,candidateFromGeometry} from '../server/vision-provider.mjs';
import {VisionJobs} from '../web/src/vision.js';import {sample,clone,pageOf,uid} from '../web/src/core.js';
const scene={schema:'vdraw-vision-provider/1',objects:[{id:'a',name:'斜めの窓',category:'建物',color:'#BACFC7'},{id:'b',name:'未検出の植栽',category:'植栽',color:'#608050'}]};
const geometry={schema:scene.schema,coordinateSpace:'drawing-1200x800',model:'mock-sam-contract',objects:[{objectId:'a',kind:'polygon',x:100,y:100,w:250,h:150,points:[[100,130],[330,100],[350,200],[120,250]]}]};
const bytes=Buffer.from('89504e470d0a1a0a','hex');const config={key:'test-only-not-a-real-key',model:'mock-claude-contract',samURL:'http://127.0.0.1/mock',samToken:'test-only',timeoutMs:40};
const consent={externalTransferApproved:true,costApproved:true};const input={bytes,mime:'image/png',sourceId:'fixture-source',consent,config};
function mock(){const calls=[];return{calls,async fetch(url,options){calls.push({url,options});return new Response(JSON.stringify(calls.length===1?{model:'mock-claude-contract',content:[{type:'text',text:JSON.stringify(scene)}],usage:{input_tokens:20,output_tokens:15}}:geometry),{status:200});}};}
test('missing environment is UNCONNECTED; no network request',()=>{const s=status({});assert.equal(s.status,'UNCONNECTED');assert.equal(s.networkRequests,0);assert.equal(s.missing.length,4);assert.equal(s.realInferenceCount,0);});
test('SAM credentials in URLs or insecure external endpoints rejected',()=>{for(const url of ['http://example.com','https://user:secret@example.com','https://example.com?key=secret'])assert.throws(()=>configuration({SAM_PROVIDER_URL:url}),e=>e.code==='INVALID_CONFIG');});
test('consent required before any provider call',async()=>{const m=mock();await assert.rejects(runVision({...input,consent:{},fetchImpl:m.fetch}),e=>e.code==='CONSENT_REQUIRED');assert.equal(m.calls.length,0);});
test('mock contracts complete actual stage transitions; no invented progress',async()=>{const m=mock(),stages=[];const result=await runVision({...input,fetchImpl:m.fetch,onStage:s=>stages.push(s)});assert.deepEqual(stages,['SCENE','SEGMENTATION','GEOMETRY','COLOR','CANDIDATE_READY']);assert.equal(m.calls.length,2);assert.deepEqual(result.candidate.missingObjects,['b']);assert.deepEqual(result.candidate.elements[0].points,geometry.objects[0].points);assert.equal(result.candidate.calibration,'UNSCALED');assert.equal(result.record.usage.input_tokens,20);assert.equal(result.record.corrections,null);const body=JSON.parse(m.calls[0].options.body);assert.equal(body.messages[0].content[0].type,'image');const c=JSON.stringify(result);assert.ok(!c.includes(config.key));assert.ok(!c.includes(config.samToken));});
test('401 stops at scene, no retry or SAM call, no response body/secrets exposed',async()=>{let calls=0;await assert.rejects(runVision({...input,fetchImpl:async()=>{calls++;return new Response('private secret from response',{status:401});}}),e=>e.code==='PROVIDER_HTTP'&&e.record.failedStage==='SCENE'&&!e.message.includes('private'));assert.equal(calls,1);});
test('timeout reported without retry',async()=>{let calls=0;await assert.rejects(runVision({...input,fetchImpl:async(url,{signal})=>{calls++;return new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(new DOMException('aborted','AbortError'))));}}),e=>e.code==='PROVIDER_TIMEOUT');assert.equal(calls,1);});
test('invalid provider JSON and SAM contract fail safely',async()=>{await assert.rejects(runVision({...input,fetchImpl:async()=>new Response('not JSON')}),e=>e.code==='PROVIDER_JSON');const m=mock();await assert.rejects(runVision({...input,fetchImpl:async(u,o)=>{const r=await m.fetch(u,o);return m.calls.length===2?new Response(JSON.stringify({...geometry,coordinateSpace:'mm'})):r;}}),e=>e.code==='GEOMETRY_INVALID'&&e.record.failedStage==='GEOMETRY');});
test('geometry rejects unknown IDs, malformed polygons and invented units',()=>{for(const g of [{...geometry,coordinateSpace:'mm'},{...geometry,objects:[{...geometry.objects[0],objectId:'bad'}]},{...geometry,objects:[{...geometry.objects[0],points:[[100,100],[1200,NaN],[100,200]]}]}])assert.throws(()=>candidateFromGeometry(scene,g,'source'));});
test('candidate receipt, adoption and discard preserve manual page; fixture labelled',async()=>{const d=sample(),before=JSON.stringify(d.pages[0]),v=new VisionJobs(),m=mock();const result=await runVision({...input,sourceId:d.pages[0].sourceId,fetchImpl:m.fetch});const envelope={schema:'vdraw-vision-result/1',executionKind:'protocol-fixture',...result};const candidate=v.receive(d,envelope);assert.equal(candidate.kind,'protocol-fixture');assert.equal(JSON.stringify(d.pages[0]),before);d.candidates.push(clone(candidate));v.adopt(d,candidate);assert.equal(d.pages.length,2);assert.equal(JSON.stringify(d.pages[0]),before);assert.equal(pageOf(d).calibration.status,'UNSCALED');d.candidates[0].status='discarded';assert.equal(JSON.stringify(d.pages[0]),before);await fs.mkdir('evidence',{recursive:true});await fs.writeFile('evidence/vision-protocol-fixture.json',JSON.stringify({label:'PROTOCOL MOCK ONLY — not real AI, not a real photo',...envelope},null,2));});
test('candidate receipt rejects wrong source and keeps existing document unchanged',()=>{const d=sample(),before=JSON.stringify(d),v=new VisionJobs();assert.throws(()=>v.receive(d,{schema:'vdraw-vision-result/1',executionKind:'protocol-fixture',record:{status:'CANDIDATE_READY'},candidate:{sourceId:uid(),elements:[],calibration:'UNSCALED'}}));assert.equal(JSON.stringify(d),before);});
