import test from 'node:test';import assert from 'node:assert/strict';
import {runVision} from '../server/vision-provider.mjs';import {rankMasks,prompts} from '../server/sam-contract.mjs';import {PhotoTrial,trialStages} from '../server/photo-trial.mjs';
const scene={schema:'vdraw-vision-provider/1',objects:[{id:'a',name:'未知の対象',category:'未知対象',color:'#8899AA',bbox:[50,50,250,250]}]},geometry={schema:scene.schema,coordinateSpace:'drawing-1200x800',model:'sam-fixture',objects:[{objectId:'a',kind:'rect',x:60,y:60,w:150,h:120}]};
const input={bytes:Buffer.from('89504e470d0a1a0a','hex'),mime:'image/png',sourceId:'fixture-source',consent:{externalTransferApproved:true,costApproved:true},config:{key:'NOT_REAL_TEST_KEY',model:'claude-fixture',samURL:'http://127.0.0.1/mock',samToken:'NOT_REAL_TEST_TOKEN',timeoutMs:25}};
function mock(second=geometry,first={model:'claude-fixture',stop_reason:'end_turn',content:[{type:'text',text:JSON.stringify(scene)}],usage:{input_tokens:11,output_tokens:22}}){let calls=0;const requests=[];return {get calls(){return calls},requests,async fetch(u,o){requests.push({u,body:JSON.parse(o.body)});return new Response(JSON.stringify(++calls===1?first:second));}};}
test('structured JSON schema/image payload/prompt bbox/usage/stage clock',async()=>{const m=mock(),events=[];const r=await runVision({...input,fetchImpl:m.fetch,onEvent:x=>events.push(x)});assert.equal(m.requests[0].body.output_config.format.type,'json_schema');assert.ok(m.requests[0].body.output_config.format.schema.properties.objects);assert.deepEqual(m.requests[1].body.prompts[0].bbox,[50,50,250,250]);assert.equal(r.record.unknownCount,1);assert.equal(r.record.sceneCount,1);assert.equal(r.record.segmentationCount,1);assert.equal(events.length,5);assert.ok(events.every(x=>x.durationMs>=0&&x.retryCount===0&&x.startedAt&&x.endedAt));assert.equal(r.record.usage.output_tokens,22);assert.ok(!JSON.stringify(r).includes(input.config.key));});
test('timeout even if fetch ignores AbortSignal; no retry',async()=>{let n=0;const t=performance.now();await assert.rejects(runVision({...input,fetchImpl:async()=>{n++;return new Promise(()=>{});}}),e=>e.code==='PROVIDER_TIMEOUT');assert.equal(n,1);assert.ok(performance.now()-t<500);});
test('SAM timeout, GPU memory failure, auth failure stop with safe codes',async()=>{for(const variant of ['timeout','memory','auth']){const m=mock();await assert.rejects(runVision({...input,fetchImpl:async(u,o)=>{if(m.calls===1){if(variant==='timeout')return new Promise(()=>{});if(variant==='auth')return new Response('PRIVATE_BODY',{status:403});return new Response(JSON.stringify({error:{code:'OUT_OF_MEMORY',detail:'PRIVATE_STACK'}}));}return m.fetch(u,o);}}),e=>e.record.failedStage==='SEGMENTATION'&&['SAM_MEMORY','PROVIDER_TIMEOUT','PROVIDER_HTTP'].includes(e.code)&&!e.message.includes('PRIVATE'));}});
test('incomplete Claude/refusal and oversized body are not candidates',async()=>{for(const stop of ['max_tokens','refusal']){const m=mock(geometry,{stop_reason:stop});await assert.rejects(runVision({...input,fetchImpl:m.fetch}),e=>e.code==='SCENE_INCOMPLETE');assert.equal(m.calls,1);}await assert.rejects(runVision({...input,fetchImpl:async()=>new Response('{}',{headers:{'content-length':String(9*1024*1024)}})}),e=>e.code==='PROVIDER_TOO_LARGE');});
const mask=score=>({objectId:'a',bbox:[60,60,220,220],score,points:[[60,60],[220,60],[200,220]]});
test('multiple masks choose highest internal ranking; no score advertised as accuracy',()=>{const r=rankMasks({schema:'vdraw-sam-masks/1',coordinateSpace:'drawing-1200x800',model:'sam-fixture',masks:[mask(.5),{...mask(.9),points:[[60,60],[220,80],[180,220]]}]},scene);assert.equal(r.maskCount,2);assert.equal(r.selectedMaskCount,1);assert.equal(r.objects[0].points[1][1],80);assert.equal(r.objects[0].score,undefined);assert.deepEqual(prompts(scene)[0].bbox,scene.objects[0].bbox);});
test('mask ID/bbox/polygon/score contract rejects misalignment',()=>{for(const m of [{...mask(.5),objectId:'missing'},{...mask(.5),score:2},{...mask(.5),bbox:[800,600,900,700],points:[[800,600],[900,600],[800,700]]},{...mask(.5),points:[[NaN,60],[220,80],[180,220]]}])assert.throws(()=>rankMasks({schema:'vdraw-sam-masks/1',coordinateSpace:'drawing-1200x800',masks:[m]},scene));});
test('trial gates human stages; unmeasured metrics stay null and logs exclude names',async()=>{const t=new PhotoTrial({executionKind:'protocol-fixture',inputKind:'synthetic-fixture'});assert.throws(()=>t.start('ADOPT'));await t.step('PHOTO',async()=>{});t.inputAccepted();const m=mock();const r=await runVision({...input,fetchImpl:m.fetch,onEvent:x=>t.providerEvent(x)});t.aiResult(r.record);assert.equal(t.report().metrics.colorCorrections,null);for(const stage of trialStages.slice(6))await t.step(stage,async()=>{});t.humanAssessment({missedObjects:0,misclassifiedObjects:0,incorrectShapes:0,colorCorrections:1,shapeCorrections:1,classCorrections:1,operatorActionCount:5,correctionTimeMs:10},{attested:true,source:'automated-fixture'});assert.equal(t.report().metrics.measuredOnRealPhoto,false);assert.ok(!JSON.stringify(t.report()).includes('未知の対象'));assert.equal(t.report().stages.length,12);});
test('input size/signature/timeout and unknown category rejected before candidate',async()=>{for(const patch of [{mime:'image/gif'},{bytes:Buffer.from('bad')},{bytes:Buffer.alloc(6*1024*1024+1)},{config:{...input.config,timeoutMs:0}}]){let n=0;await assert.rejects(runVision({...input,...patch,fetchImpl:async()=>{n++;}}));assert.equal(n,0);}const m=mock(geometry,{content:[{type:'text',text:JSON.stringify({...scene,objects:[{...scene.objects[0],category:'unlisted'}]})}]});await assert.rejects(runVision({...input,fetchImpl:m.fetch}),e=>e.code==='SCENE_INVALID');});
