import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {drawingIRToReviewDXF,REVIEW_POLICY} from '../mm-geometry-review.mjs';
import {validateDrawingIR} from '../../../drawing-ir/candidate-2/validate.mjs';
const load=id=>JSON.parse(readFileSync(new URL('../../../docs/architecture/tracks/B/candidate2-evidence/'+id+'.adapter-result.json',import.meta.url)));
const G04=()=>JSON.parse(readFileSync(new URL('../fixtures/synthetic-g04-property-witness.adapter-result.json',import.meta.url)));
// Independent test lexer: no writer helper import, and source mathematics supplies expected numbers.
function parse(text){const lines=text.trimEnd().split('\n');assert.equal(lines.length%2,0);assert.ok(/^[\x09\x0a\x0d\x20-\x7e]*$/.test(text));const pairs=[];for(let i=0;i<lines.length;i+=2){assert.ok(/^\d+$/.test(lines[i]));pairs.push([Number(lines[i]),lines[i+1]]);}const start=pairs.findIndex((p,i)=>p[0]===0&&p[1]==='SECTION'&&pairs[i+1]?.[1]==='ENTITIES');assert.ok(start>=0);const records=[];for(let i=start+2;i<pairs.length;i++){const[c,v]=pairs[i];if(c===0&&v==='ENDSEC')break;if(c===0)records.push({kind:v,pairs:[]});else records.at(-1).pairs.push([c,v]);}return {pairs,records};}
const value=(r,c)=>r.pairs.find(p=>p[0]===c)?.[1],num=(r,c)=>Number(value(r,c)),near=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`);
function logical(a){const rs=parse(a.asciiDXF).records,out=[];for(let i=0;i<rs.length;i++){const r=rs[i];if(r.kind==='POLYLINE'){const vs=[];let j=i+1;for(;rs[j]?.kind==='VERTEX';j++)vs.push(rs[j]);assert.equal(rs[j]?.kind,'SEQEND');out.push({r,vertices:vs});i=j;}else{assert.ok(['LINE','CIRCLE'].includes(r.kind));out.push({r});}}return out;}
const digest=text=>createHash('sha256').update(text).digest('hex');
const specs=[['generic-synthetic-g01',4,1],['generic-synthetic-g02-nested',3,1],['native-vdraw-n01',5,1],['synthetic-g03-expanded',6,2],['explicit-paint-width-alpha-witness',1,1]];
for(const[id,count,pages]of specs)test('fixed source '+id+' produces nonzero geometry with fullsource/property ledger',async()=>{const s=load(id),before=JSON.stringify(s),r=await drawingIRToReviewDXF(s);assert.equal(r.manifest.packageLogicalEntityCount,count);assert.equal(r.artifacts.length,pages);assert.equal(r.manifest.sourceDenominators.allInventory,s.document.sourceInventory.length);assert.equal(r.manifest.packageRetentionLedger.length,s.document.sourceInventory.length);assert.equal(r.manifest.propertyLossLedger.length,s.document.sourceInventory.length);assert.ok(r.manifest.propertyLossLedger.every(row=>row.properties.length===6&&row.properties.every(p=>p.retention==='NOT_RETAINED')));assert.deepEqual(r.manifest.sourceInventory,s.document.sourceInventory);assert.deepEqual(r.manifest.sourceLedger,s.document.sourceLedger);assert.equal(r.productGate,'HOLD');assert.equal(r.actualJwCad,'NOT_RUN');assert.equal(r.manifest.completeAppearanceFidelity,false);assert.equal(JSON.stringify(s),before);assert.equal(r.evaluationValidation.ok,true);for(const a of r.artifacts){assert.equal(a.sha256,digest(a.asciiDXF));assert.equal(logical(a).length,a.logicalEntityCount);assert.equal(parse(a.asciiDXF).records.length,a.rawEntityRecordCount);assert.equal(a.coordinatePhysicalUnit,'MM');assert.equal(a.coordinateUnitRole,'LAYOUT');assert.equal(a.scaleStatus,'UNSCALED');assert.equal(a.yAxis,'UP');}});
test('independent direct witness four corners are raw EMU/36000 and exactly one CAD reflection',async()=>{const s=load('explicit-paint-width-alpha-witness'),r=await drawingIRToReviewDXF(s),l=logical(r.artifacts[0])[0];assert.equal(l.r.kind,'POLYLINE');assert.equal(value(l.r,70),'1');const expected=[[36000,72000],[144000,72000],[144000,216000],[36000,216000]].map(([x,y])=>[x/36000,7315200/36000-y/36000]);assert.equal(l.vertices.length,4);l.vertices.forEach((v,i)=>{near(num(v,10),expected[i][0]);near(num(v,20),expected[i][1]);});});
test('grouped/rotated polygons preserve ordered full corners from validated geometry',async()=>{const s=load('generic-synthetic-g02-nested'),r=await drawingIRToReviewDXF(s);for(const map of r.manifest.sourceToEntityMapping.filter(e=>e.entityType==='POLYLINE')){const o=s.document.objects.find(o=>o.id===map.objectId),a=r.artifacts.find(a=>a.filename===map.filename),l=logical(a).find(x=>value(x.r,5)===map.rawHandles[0]);assert.equal(l.vertices.length,o.drawingGeometry.points.length);l.vertices.forEach((v,i)=>{near(num(v,10),o.drawingGeometry.points[i][0]);near(num(v,20),o.drawingGeometry.points[i][1]);});}});
test('circle primitive exports center/radius directly, with finite positive radius',async()=>{const s=load('generic-synthetic-g01'),r=await drawingIRToReviewDXF(s),map=r.manifest.sourceToEntityMapping.find(e=>e.entityType==='CIRCLE');assert.ok(map);const o=s.document.objects.find(o=>o.id===map.objectId),rec=parse(r.artifacts.find(a=>a.filename===map.filename).asciiDXF).records.find(r=>value(r,5)===map.rawHandles[0]);near(num(rec,10),o.drawingGeometry.center[0]);near(num(rec,20),o.drawingGeometry.center[1]);near(num(rec,40),o.drawingGeometry.radius);assert.ok(num(rec,40)>0);});
test('text/ellipse/custom/background/hidden remain explicit target unsupported or Human check',async()=>{const s=load('native-vdraw-n01'),r=await drawingIRToReviewDXF(s);const ellipse=s.document.objects.find(o=>o.kind==='ellipse');assert.ok(ellipse);const mapped=r.manifest.packageRetentionLedger.find(row=>row.sourceBinding.partPath===ellipse.sourceBinding.partPath);assert.equal(mapped.status,'UNSUPPORTED');assert.equal(mapped.logicalEntityIds.length,0);assert.equal(mapped.reason,'UNSUPPORTED_DXF_REVIEW_GEOMETRY_ELLIPSE');assert.ok(r.manifest.propertyLossLedger.filter(p=>p.sourceComponentKind==='text').every(p=>p.sourceRawText&&p.properties.find(q=>q.property==='font').retention==='NOT_RETAINED'));const g=await drawingIRToReviewDXF(load('synthetic-g03-expanded'));assert.equal(g.manifest.packageRetentionLedger.filter(l=>l.reason==='CUSTOM_PATH_COORDINATE_FRAME_UNREPRESENTABLE').length,2);assert.ok(g.manifest.packageRetentionLedger.some(l=>l.reason==='BACKGROUND_POLICY_REQUIRED'));});
test('every per-page evaluation retains global inventory and names other page file/hash',async()=>{const s=load('synthetic-g03-expanded'),r=await drawingIRToReviewDXF(s);assert.equal(r.artifacts.length,2);assert.notEqual(r.artifacts[0].filename,r.artifacts[1].filename);for(const e of r.evaluatedIR.exportEvaluations){assert.equal(e.requiredInventoryIds.length,s.document.sourceInventory.length);assert.equal(e.retentionLedger.length,s.document.sourceInventory.length);const p=r.manifest.pages.find(p=>p.coordinateFrameId===e.targetFrameId);assert.equal(p.requiredGlobalInventoryCount,s.document.sourceInventory.length);for(const row of e.retentionLedger){const item=s.document.sourceInventory.find(i=>i.id===row.inventoryId);if(item.sourceBinding.pageId!==p.pageId){const other=r.artifacts.find(a=>a.pageId===item.sourceBinding.pageId);assert.equal(row.status,'EXCLUDED_BY_POLICY');assert.ok(row.reason.includes(other.filename)&&row.reason.includes(other.sha256));}}}assert.equal(validateDrawingIR(r.evaluatedIR).ok,true);});
test('raw POLYLINE/VERTEX/SEQEND handles are all individually mapped to source component',async()=>{const r=await drawingIRToReviewDXF(load('synthetic-g03-expanded'));for(const a of r.artifacts){const records=parse(a.asciiDXF).records;assert.equal(new Set(records.map(r=>value(r,5))).size,records.length);for(const rec of records){const binding=a.rawRecords.find(r=>r.handle===value(rec,5));assert.ok(binding);assert.equal(binding.recordType,rec.kind);assert.ok(binding.inventoryId&&binding.objectId&&binding.sourceBinding);assert.ok(a.logicalEntities.some(e=>e.id===binding.logicalEntityId&&e.rawHandles.includes(binding.handle)));}}assert.ok(r.manifest.packageRawEntityRecordCount>r.manifest.packageLogicalEntityCount);});
test('generated review attributes never approximate actual source truecolor/width/dash/opacity',async()=>{const r=await drawingIRToReviewDXF(load('explicit-paint-width-alpha-witness'));assert.equal(REVIEW_POLICY.ACI,7);for(const rec of parse(r.artifacts[0].asciiDXF).records){assert.equal(value(rec,8),'VDRAW_REVIEW_GEOMETRY');assert.equal(value(rec,62),'7');assert.equal(value(rec,6),'CONTINUOUS');assert.equal(value(rec,420),undefined);assert.equal(value(rec,370),undefined);}const row=r.manifest.propertyLossLedger.find(l=>l.logicalEntityIds.length);assert.equal(row.properties.find(p=>p.property==='strokeColor').sourceValue,'#ABCDef');assert.equal(row.properties.find(p=>p.property==='strokeColor').retention,'NOT_RETAINED');assert.equal(row.properties.find(p=>p.property==='width').sourceValue,3600);assert.equal(row.properties.find(p=>p.property==='opacity').sourceValue,.75);});
test('G04 explicit no-paint visibility override is policy-bound and differing alpha stays raw unresolved',async()=>{const s=G04(),r=await drawingIRToReviewDXF(s);assert.equal(r.manifest.packageLogicalEntityCount,3);assert.ok(r.manifest.propertyLossLedger.some(l=>l.reviewOutlineOverride));assert.ok(!r.manifest.propertyLossLedger.some(l=>l.reviewVisibilityOverride));const o=s.document.objects.find(o=>o.style.stroke&&o.style.fill);assert.ok(o);assert.equal(o.style.opacity,null);const row=r.manifest.propertyLossLedger.find(row=>row.sourceIRObjectId===o.id);assert.equal(row.properties.find(p=>p.property==='opacity').sourceValue,null);assert.equal(row.properties.find(p=>p.property==='opacity').sourceResolution.state,'UNRESOLVED');});
test('deterministic ASCII DXF and safe stable file/handle identity do not rely on time/randomness',async()=>{const s=load('generic-synthetic-g01'),a=await drawingIRToReviewDXF(s),b=await drawingIRToReviewDXF(s);assert.deepEqual(a,b);for(const f of a.artifacts){assert.ok(/^[a-z0-9-]+\.dxf$/.test(f.filename));assert.ok(!f.filename.includes('..'));assert.equal(f.sha256,digest(f.asciiDXF));const pairs=parse(f.asciiDXF).pairs;assert.equal(pairs.find(p=>p[0]===9)?.[1],'$ACADVER');assert.ok(pairs.some(p=>p[0]===1&&p[1]==='AC1009'));assert.ok(!f.asciiDXF.includes('$INSUNITS'));assert.ok(a.manifest.limitations.some(i=>i.code==='UNIT_HEADER_METADATA_UNAVAILABLE'));}});
const bad=[['nonfinite coordinates',s=>s.document.objects[0].drawingGeometry.points[0][0]=NaN,'UNSAFE_OUTPUT_COORDINATE'],['unsafe coordinates',s=>s.document.objects[0].drawingGeometry.points[0][0]=1e20,'UNSAFE_OUTPUT_COORDINATE'],['wrong target unit',s=>s.document.frames.find(f=>f.id===s.document.objects[0].frameId).physicalUnit='EMU','PINNED_IR_CONTRACT_REJECTED'],['wrong target axis',s=>s.document.frames.find(f=>f.id===s.document.objects[0].frameId).yAxis='DOWN','LAYOUT_MM_AXIS_TRANSFORM_MISMATCH'],['unknown transform scope',s=>s.document.transforms[0].provenance.method='UNREVIEWED','UNREVIEWED_TRANSFORM_SCOPE'],['calibrated claim',s=>s.document.scaleStatus='CALIBRATED','REAL_WORLD_OR_CALIBRATION_OUT_OF_SCOPE'],['real world claim',s=>s.document.frames.find(f=>f.id===s.document.objects[0].frameId).unitRole='REAL_WORLD','REAL_WORLD_OR_CALIBRATION_OUT_OF_SCOPE'],['existing FULL evaluation',s=>s.document.exportEvaluations.push({readiness:'FULL'}),'INPUT_EXPORT_READINESS_ALREADY_ASSERTED'],['unit pin mismatch',s=>s.manifest.irPin.head='wrong','UNREVIEWED_INPUT_CONTRACT_PIN'],['source identity mismatch',s=>s.nativeSource.source.sha256='0'.repeat(64),'SOURCE_HASH_BINDING_MISMATCH'],['omitted global source item',s=>s.manifest.parts.pop(),'FULL_SOURCE_DENOMINATOR_MISMATCH'],['promoted product gate',s=>s.productGate='PASS','INPUT_GATE_PROMOTION_FORBIDDEN']];
for(const[name,mutate,code]of bad)test('fail closed '+name,async()=>{const s=load('explicit-paint-width-alpha-witness');mutate(s);await assert.rejects(drawingIRToReviewDXF(s),e=>e.code===code,code);});
test('requested FULL or production readiness is rejected before output',async()=>{await assert.rejects(drawingIRToReviewDXF(load('native-vdraw-n01'),{requestedReadiness:'FULL'}),e=>e.code==='REVIEW_FULL_OR_PRODUCT_READINESS_FORBIDDEN');});
test('source IR retained while export evaluations remain strictly PARTIAL/BLOCKED',async()=>{const s=load('native-vdraw-n01'),r=await drawingIRToReviewDXF(s);for(const key of Object.keys(s.document).filter(k=>!['evidence','exportEvaluations'].includes(k)))assert.deepEqual(r.evaluatedIR[key],s.document[key]);assert.ok(r.evaluatedIR.exportEvaluations.every(e=>e.readiness==='PARTIAL'));assert.equal(s.document.exportEvaluations.length,0);});
// Synthetic IR contract witnesses exercise target syntax only, not authentication of an OOXML source.
test('synthetic native-EMU open polyline contract produces flag0 and all ordered vertices',async()=>{const s=load('explicit-paint-width-alpha-witness'),o=s.document.objects[0];o.kind='polyline';o.nativeGeometry.kind='polyline';o.nativeGeometry.closed=false;o.drawingGeometry.kind='polyline';o.drawingGeometry.closed=false;assert.equal(validateDrawingIR(s.document).ok,true);const r=await drawingIRToReviewDXF(s),l=logical(r.artifacts[0])[0];assert.equal(l.r.kind,'POLYLINE');assert.equal(value(l.r,70),'0');assert.equal(l.vertices.length,4);l.vertices.forEach((v,i)=>{near(num(v,10),o.drawingGeometry.points[i][0]);near(num(v,20),o.drawingGeometry.points[i][1]);});assert.equal(r.productGate,'HOLD');});
test('synthetic odd-radius circle contract remains blocked if inconsistent with source transform',async()=>{const s=load('generic-synthetic-g01'),o=s.document.objects.find(o=>o.kind==='circle');o.drawingGeometry.radius=-1;await assert.rejects(drawingIRToReviewDXF(s),e=>e.code==='PINNED_IR_CONTRACT_REJECTED');});
test('nonzero ellipse-only source produces explicit BLOCKED empty output rather than readiness PASS',async()=>{const s=load('native-vdraw-n01');const keep=s.document.objects.find(o=>o.kind==='ellipse');for(const o of s.document.objects.filter(o=>o.id!==keep.id)){const row=s.document.sourceLedger.find(l=>l.objectIds.includes(o.id)),item=s.document.sourceInventory.find(i=>i.id===row.inventoryId);row.disposition='HUMAN_CHECK_REQUIRED';row.objectIds=[];row.reason='SYNTHETIC_TEST_OTHER_GEOMETRY_HELD';row.nextHumanAction='Synthetic IR-only target contract test';item.support='HUMAN_CHECK_REQUIRED';item.reason=row.reason;item.nextHumanAction=row.nextHumanAction;}s.document.objects=[keep];for(const page of s.document.pages)page.objectIds=page.objectIds.filter(id=>id===keep.id);assert.equal(validateDrawingIR(s.document).ok,true);const r=await drawingIRToReviewDXF(s);assert.equal(r.manifest.packageLogicalEntityCount,0);assert.equal(r.manifest.exportStatus,'BLOCKED_NO_SUPPORTED_ENTITIES');assert.equal(r.evaluatedIR.exportEvaluations[0].readiness,'BLOCKED');assert.equal(r.productGate,'HOLD');});
test('duplicate/misordered source-page indexes cannot overlay output filenames',async()=>{const s=load('synthetic-g03-expanded');s.document.pages[1].index=0;await assert.rejects(drawingIRToReviewDXF(s),e=>e.code==='SOURCE_PAGE_ORDER_OR_PARTITION_MISMATCH');});
test('declared layout extent must match physical source slide EMU/36000',async()=>{const s=load('explicit-paint-width-alpha-witness'),f=s.document.frames.find(f=>f.id===s.document.objects[0].frameId);f.extent[0]++;await assert.rejects(drawingIRToReviewDXF(s),e=>e.code==='SOURCE_PAGE_LAYOUT_MM_EXTENT_MISMATCH');});
