import test from 'node:test';import assert from 'node:assert/strict';import path from 'node:path';import{pathToFileURL}from'node:url';
import{fixture,unknown,target}from'../fixtures/independent-style-scaffold.mjs';
const root=process.env.VDRAW_A2_FIXED_ROOT;if(!root)throw Error('VDRAW_A2_FIXED_ROOT required');
const{validateDrawingIR:v}=await import(pathToFileURL(path.join(root,'validate.mjs')));
const good=d=>{const before=JSON.stringify(d),r=v(d);assert.equal(r.ok,true,JSON.stringify(r.errors));assert.equal(r.productGate,'HOLD');assert.equal(JSON.stringify(d),before);return r;};
const bad=d=>{const before=JSON.stringify(d),r=v(d);assert.equal(r.ok,false,JSON.stringify(d));assert.equal(JSON.stringify(d),before);return r;};
test('G synthetic explicit scaffold retains negative line and contract HOLD',()=>good(fixture()));
test('known geometry survives all five honest unresolved style fields',()=>{let d=fixture();for(const f of ['stroke','fill','width','dash','opacity'])d=unknown(f,d);good(d);assert.equal(d.objects.length,1);assert.deepEqual(d.objects[0].drawingGeometry,{kind:'line',start:[-1,0],end:[2,1]});});
test('explicit noFill differs from unknown null paint',()=>{const a=fixture(),b=unknown('fill');good(a);good(b);assert.notDeepEqual(a.objects[0].style.resolution.fill,b.objects[0].style.resolution.fill);});
for(const f of ['stroke','fill','width','dash','opacity'])test('unknown '+f+' cannot become guessed numeric/default drawable field',()=>{const d=unknown(f);d.objects[0].style[f]=fixture().objects[0].style[f]===null?'#FFFFFF':fixture().objects[0].style[f];bad(d);});
test('unresolved null missing issue fails',()=>{const d=unknown();d.issues=[];bad(d);});
test('unresolved issue for different inventory does not qualify',()=>{const d=unknown();d.issues[0].inventoryId=null;bad(d);});
test('unresolved style on KNOWN status fails',()=>{const d=unknown();d.objects[0].status='KNOWN';bad(d);});
test('unresolved raw source lexeme fabrication fails',()=>{const d=unknown();d.objects[0].style.resolution.opacity.rawLexeme='100000';bad(d);});
test('null opacity under EXPLICIT nonmatching decoded value fails',()=>{const d=fixture();d.objects[0].style.opacity=null;bad(d);});
test('explicit width without lexeme fails',()=>{const d=fixture();d.objects[0].style.resolution.width.rawLexeme=null;bad(d);});
test('provenance missing propertyPath fails',()=>{const d=fixture();delete d.objects[0].style.resolution.width.propertyPath;bad(d);});
test('provenance empty propertyPath fails',()=>{const d=fixture();d.objects[0].style.resolution.width.propertyPath='';bad(d);});
test('missing property source binding fails',()=>{const d=fixture();delete d.objects[0].style.resolution.width.sourceBinding;bad(d);});
test('forged different native source identity fails',()=>{const d=fixture();d.objects[0].style.resolution.width.sourceBinding.nativeObjectId='other';bad(d);});
test('forged property source hash fails',()=>{const d=fixture();d.objects[0].style.resolution.width.sourceBinding.sha256='c'.repeat(64);bad(d);});
test('forged different component binding fails',()=>{const d=fixture();d.objects[0].style.resolution.width.sourceBinding.partPath='different';bad(d);});
test('missing property evidence fails',()=>{const d=fixture();d.objects[0].style.resolution.width.evidenceIds=[];bad(d);});
test('dangling property evidence fails',()=>{const d=fixture();d.objects[0].style.resolution.width.evidenceIds=['missing'];bad(d);});
test('source evidence wrong hash fails',()=>{const d=fixture();d.evidence[0].sha256='c'.repeat(64);bad(d);});
test('source evidence wrong method fails',()=>{const d=fixture();d.evidence[0].method='MODEL_SCORE';bad(d);});
test('SPEC_DEFAULT stays disabled even with named policy',()=>{const d=fixture();Object.assign(d.objects[0].style.resolution.width,{state:'SPEC_DEFAULT',encoding:'SPEC_DEFAULT',policyId:'pretend-spec',reason:'default claimed'});bad(d);});
test('honest unresolved style cannot claim FULL',()=>bad(target(unknown())));
test('honest unresolved style permits PARTIAL contract HOLD',()=>good(target(unknown(),'PARTIAL')));
test('known style with unresolved issue cannot claim FULL',()=>{const d=target(fixture());d.issues=[{id:'unresolved',code:'UNRESOLVED_OTHER_ATTRIBUTE',inventoryId:'geometry',reason:'unknown',nextHumanAction:'review',evidenceIds:['xml']}];bad(d);});
test('known style with unsupported issue cannot claim FULL',()=>{const d=target(fixture());d.issues=[{id:'unsupported',code:'UNSUPPORTED_OBJECT',inventoryId:'geometry',reason:'unsupported',nextHumanAction:'review',evidenceIds:['xml']}];bad(d);});
test('unknown stroke cannot justify width NOT_APPLICABLE',()=>{const d=unknown('stroke');d.objects[0].style.width=null;Object.assign(d.objects[0].style.resolution.width,{state:'NOT_APPLICABLE',encoding:'NOT_APPLICABLE',rawLexeme:null,reason:'wrongly absent paint'});bad(d);});
test('explicit noFill stroke permits width and dash NOT_APPLICABLE',()=>{const d=fixture(),s=d.objects[0].style;s.stroke=null;Object.assign(s.resolution.stroke,{encoding:'OOXML_NO_FILL',rawLexeme:'noFill'});for(const f of ['width','dash']){s[f]=null;Object.assign(s.resolution[f],{state:'NOT_APPLICABLE',encoding:'NOT_APPLICABLE',rawLexeme:null,reason:'Explicit noFill stroke'});}good(d);});
test('native OOXML solid lexeme cannot masquerade as DASH_JSON []',()=>{const d=fixture();d.objects[0].style.resolution.dash.rawLexeme='solid';bad(d);});
test('decoded dash lexical mismatch fails',()=>{const d=fixture();d.objects[0].style.resolution.dash.rawLexeme='[1,2]';bad(d);});
test('width source unit label mismatch fails',()=>{const d=fixture();d.objects[0].style.widthUnit='MM';bad(d);});
test('unknown style does not allow geometry endpoint loss',()=>{const d=unknown();d.objects[0].drawingGeometry.end=[1,1];bad(d);});
test('unknown style does not allow label-only mm conversion',()=>{const d=unknown();d.objects[0].drawingGeometry.end=[72000,36000];bad(d);});
test('unknown style does not allow REAL_WORLD promotion',()=>{const d=unknown();d.frames[1].unitRole='REAL_WORLD';bad(d);});
test('unknown style does not allow fake CALIBRATED summary',()=>{const d=unknown();d.scaleStatus='CALIBRATED';bad(d);});
test('unknown style does not allow narrowed source inventory',()=>{const d=unknown();d.sourceInventory=[];d.sourceLedger=[];d.pages[0].inventoryIds=[];bad(d);});
test('text anchors remain nonnullable after delta',()=>{const d=unknown();d.objects[0].nativeGeometry={kind:'text',content:'日本語',anchor:null,baseline:[0,0],size:36000,fontFamily:'Synthetic',lineBreaks:'PRESERVED',runs:[]};bad(d);});
test('internal lexical/source consistency never authenticates XML assertion',()=>{const d=fixture();d.evidence[0].uri='synthetic://untrusted-producer-assertion';good(d);assert.equal(v(d).scope,'IR_CONTRACT_ONLY');});
