import {IR_VERSION} from '../version.mjs';
export const H='a'.repeat(64);
export const bind=(nativeObjectId='shape1',partPath='/spTree/sp[1]/geometry')=>({sourceAssetId:'asset1',sha256:H,pageId:'slide1',nativeObjectId,partPath});
export function numbers(g){const out=[];const walk=(v,path)=>{if(typeof v==='number')out.push({path,lexeme:String(v),value:v});else if(Array.isArray(v))v.forEach((x,i)=>walk(x,`${path}/${i}`));else if(v&&typeof v==='object')for(const [k,x]of Object.entries(v))walk(x,`${path}/${k}`);};walk(g,'');return out;}
export const I=[1,0,0,0,1,0,0,0,1];
export function fixture(){
 return {schemaVersion:IR_VERSION,contractStatus:'CANDIDATE',documentId:'doc1',sourceType:'PPTX',scaleStatus:'UNSCALED',sourceAssets:[{id:'asset1',sha256:H,mediaType:'application/vnd.openxmlformats-officedocument.presentationml.presentation',sourceType:'PPTX',immutableUri:'fixture://pptx1'}],pages:[{id:'slide1',sourceAssetId:'asset1',index:0,objectIds:['line1'],inventoryIds:['part1']}],frames:[{id:'native1',physicalUnit:'EMU',unitRole:'SOURCE',origin:[0,0],yAxis:'DOWN',extent:[72000,72000],pageId:'slide1'},{id:'layout1',physicalUnit:'MM',unitRole:'LAYOUT',origin:[0,0],yAxis:'DOWN',extent:[2,2],pageId:'slide1'}],calibrations:[],transforms:[{id:'emu-mm',fromFrameId:'native1',toFrameId:'layout1',type:'AFFINE',matrix:[1/36000,0,0,0,1/36000,0,0,0,1],convention:'ROW_MAJOR_COLUMN_VECTOR',composition:'NEXT_TIMES_PREVIOUS',invertible:true,provenance:{method:'KNOWN_EMU_LAYOUT_UNIT',evidenceIds:['ev1']},validRegion:null,calibrationId:null}],layers:[{id:'layer1',name:'fixture',provenance:'SYNTHETIC',evidenceIds:[]}],objects:[{id:'line1',kind:'line',sourceBinding:bind(),sourceFrameId:'native1',frameId:'layout1',nativeGeometry:{kind:'line',start:[0,0],end:[36000,0]},nativeNumbers:numbers({kind:'line',start:[0,0],end:[36000,0]}),drawingGeometry:{kind:'line',start:[0,0],end:[1,0]},transformIds:['emu-mm'],layerId:'layer1',category:'UNKNOWN',rotation:{value:0,unit:'DEG',direction:'CW',pivot:[0,0]},style:{stroke:'#123456',fill:null,width:0,widthUnit:'MM',dash:[],opacity:1,semanticColor:'UNKNOWN',evidenceIds:[]},confidence:{value:null,method:'NOT_MEASURED',measurementStatus:'UNMEASURED'},status:'KNOWN',relationshipIds:[]}],sourceInventory:[{id:'part1',sourceBinding:bind(),role:'DRAWABLE_PART',parentId:null,support:'SUPPORTED',reason:null,nextHumanAction:null}],sourceLedger:[{inventoryId:'part1',disposition:'REPRESENTED',objectIds:['line1'],reason:null,nextHumanAction:null,policyEvidenceId:null}],relationships:[],issues:[],exportEvaluations:[{id:'eval1',targetType:'DXF',targetFrameId:'layout1',unitRole:'LAYOUT',requiredInventoryIds:['part1'],readiness:'FULL',retentionLedger:[{inventoryId:'part1',status:'EXPORTED',entityIds:['entity1'],reason:null,nextHumanAction:null}],outputEntities:[{id:'entity1',inventoryId:'part1',objectId:'line1'}]}],evidence:[{id:'ev1',sha256:H,uri:'fixture://independent-unit-definition',method:'UNIT_SPECIFICATION'}]};
}
export function nativeFixture(geometry){const d=fixture();d.frames=d.frames.slice(0,1);d.transforms=[];d.exportEvaluations=[];const o=d.objects[0];o.kind=geometry.kind;o.nativeGeometry=structuredClone(geometry);o.drawingGeometry=structuredClone(geometry);o.nativeNumbers=numbers(geometry);o.frameId='native1';o.transformIds=[];o.style.widthUnit='EMU';return d;}
export function calibrated(){const d=fixture();d.scaleStatus='CALIBRATED';d.frames[1].unitRole='REAL_WORLD';d.calibrations=[{id:'cal1',provenance:'USER_INPUT',scope:{frameId:'native1',objectIds:['line1']},referenceBinding:bind(),evidenceIds:['ev1'],referenceValueMM:1,observedValue:36000,observedValueUnit:'EMU',mmPerSourceUnit:1/36000,reviewedBy:'fixture-human',uncertaintyMM:0.01}];d.evidence.push({id:'cal-ev',sha256:H,uri:'fixture://human-measurement',method:'CALIBRATION_USER_INPUT'});d.calibrations[0].evidenceIds=['cal-ev'];d.transforms[0].calibrationId='cal1';d.exportEvaluations[0].unitRole='REAL_WORLD';return d;}
