import unittest,json,copy,sys,zipfile,hashlib,math
from pathlib import Path
sys.path.insert(0,str(Path(__file__).parent))
from source_truth import truth
sys.path.insert(0,str(Path(__file__).resolve().parents[2]/'tools'))
from independent_oracle import compare_reference
R=Path(__file__).resolve().parents[1];T=json.loads((R/'fixtures/synthetic-g03-source-truth.json').read_text());D=json.loads((R/'fixtures/synthetic-g03-design-truth.json').read_text())
def obj(i,s=1):return next(o for o in T['sourceObjects'] if o['nativeId']==str(i) and o['partPath']==f'ppt/slides/slide{s}.xml')
class SourceTruthTests(unittest.TestCase):
 def test_fixture_sha(self):self.assertEqual(T['sourceHash'],hashlib.sha256((R/'fixtures/synthetic-g03-expanded.pptx').read_bytes()).hexdigest())
 def test_truth_replay(self):self.assertEqual(T,truth(R/'fixtures/synthetic-g03-expanded.pptx'))
 def test_order_not_filename(self):self.assertEqual(T['presentationOrder'],D['presentationOrder'])
 def test_physical_unit(self):self.assertEqual(T['sourceUnit'],'EMU');self.assertEqual(T['layoutMm'],[200,150])
 def test_real_world_unscaled(self):self.assertEqual(T['realWorldScaleStatus'],'UNSCALED')
 def test_open_path(self):p=obj(2)['geometryPaths'][0];self.assertEqual(p['verticesPathUnits'],D['openCustomPath']['vertices']);self.assertFalse(p['closed'])
 def test_closed_path(self):self.assertTrue(obj(3)['geometryPaths'][0]['closed'])
 def test_open_endpoints_mm(self):self.assertEqual(obj(2)['geometryPaths'][0]['globalVerticesMm'],[[-1,2],[2,2],[0.2,4]])
 def test_triangle_preset(self):self.assertEqual(obj(4)['preset'],'triangle')
 def test_negative_offset(self):self.assertEqual(obj(5)['xfrm']['x'],-36000)
 def test_angles(self):self.assertEqual([obj(i)['xfrm']['rot']/60000 for i in [5,6,7]],D['anglesDeg'])
 def test_flip_negative_direction(self):p=obj(5)['orderedCornersMm'];self.assertEqual(p[0],[2,2]);self.assertEqual(p[1],[-1,2])
 def test_ninety_degree_basis(self):b=obj(6)['basisEmu'][0];self.assertAlmostEqual(b[0],0,delta=1e-7);self.assertAlmostEqual(b[1],-108000,delta=1e-7)
 def test_359_degree_not_zero(self):self.assertGreater(abs(obj(7)['basisEmu'][0][1]),1000)
 def test_nested_hand_origin(self):self.assertListEqual(obj(4,2)['orderedCornersEmu'][0],D['nestedBasisHandAlgebra']['globalOriginEmu'])
 def test_nested_hand_basis(self):b=obj(4,2)['basisEmu'];expected=D['nestedBasisHandAlgebra'];[self.assertAlmostEqual(a,e,delta=1e-7) for a,e in zip(b[0],expected['globalBasisXEmu'])];[self.assertAlmostEqual(a,e,delta=1e-7) for a,e in zip(b[1],expected['globalBasisYEmu'])]
 def test_arc_geometry_and_text_denominator(self):self.assertEqual([p['kind'] for p in obj(8)['expectedComponents']],['geometry','text']);self.assertEqual(obj(8)['preset'],'arc')
 def test_curve_geometry_retained(self):self.assertTrue(obj(9)['geometryPaths'][0]['unsupported']);self.assertIn('cubicBezTo',obj(9)['rawCustomGeometry'])
 def test_text_exact_structure(self):t=obj(10)['parts'][1]['text'];self.assertEqual(t['content'],D['exactText']);self.assertEqual([len(p) for p in t['paragraphs']],[4,1]);self.assertEqual(t['paragraphs'][0][2]['kind'],'break')
 def test_raw_theme_not_resolved(self):c=obj(11)['style'][0];self.assertEqual(c['colorType'],'schemeClr');self.assertEqual(c['transforms'][0]['kind'],'tint');self.assertIn('UNRESOLVED',obj(11)['styleResolution'])
 def test_theme_master_dependency(self):paths=[p['path'] for p in T['rawDependencyParts']];self.assertIn('ppt/theme/theme1.xml',paths);self.assertIn('ppt/slideMasters/slideMaster1.xml',paths)
 def test_background_separate(self):self.assertEqual(T['denominators']['backgrounds'],1)
 def test_unknown_object_component(self):self.assertEqual(obj(12)['expectedComponents'][0]['kind'],'unsupported')
 def test_source_components(self):self.assertEqual(T['denominators']['sourceObjects'],15);self.assertEqual(T['denominators']['components'],17)
 def test_same_count_wrong_position_rejected(self):x=copy.deepcopy(T);x['sourceObjects'][0]['xfrm']['x']+=1;self.assertEqual(compare_reference(T,x)['status'],'FAIL')
 def test_erased_text_rejected(self):x=copy.deepcopy(T);o=next(o for o in x['sourceObjects'] if len(o['parts'])==2);o['parts'][1]['text']['content']='';self.assertEqual(compare_reference(T,x)['status'],'FAIL')
 def test_unknown_loss_rejected(self):x=copy.deepcopy(T);x['sourceObjects']=[o for o in x['sourceObjects'] if o['nativeId']!='12'];self.assertEqual(compare_reference(T,x)['status'],'FAIL')
 def test_erased_ledger_reason_rejected(self):x=copy.deepcopy(T);o=next(o for o in x['sourceObjects'] if o['nativeId']=='12');o['parts'][0]['reason']='';self.assertEqual(compare_reference(T,x)['status'],'FAIL')
 def test_label_only_unit_rejected(self):x=copy.deepcopy(T);x['sourceUnit']='MM';self.assertEqual(compare_reference(T,x)['status'],'FAIL')
 def test_fake_calibration_rejected(self):x=copy.deepcopy(T);x['realWorldScaleStatus']='CALIBRATED';self.assertEqual(compare_reference(T,x)['status'],'FAIL')
 def test_product_held(self):self.assertEqual(T['productGate'],'HOLD');self.assertEqual(T['realAppEvidence'],'NOT_RUN')
if __name__=='__main__':unittest.main()
