// G-owned independent adverse cases. The imported fixture is schema scaffolding;
// expected geometry and rejection conditions below are independently specified.
import test from 'node:test';import assert from 'node:assert/strict';import path from 'node:path';import {pathToFileURL} from 'node:url';
const root=process.env.VDRAW_IR_ROOT;if(!root)throw Error('VDRAW_IR_ROOT must identify reviewed A candidate');
const {validateDrawingIR,compose,mapPoint}=await import(pathToFileURL(path.join(root,'validate.mjs')));
const {fixture,nativeFixture,numbers}=await import(pathToFileURL(path.join(root,'tests/fixtures.mjs')));
function derived(g,m,dg){const d=nativeFixture(g);d.frames.push({...structuredClone(d.frames[0]),id:'derived'});d.transforms=[{id:'qa-transform',fromFrameId:'native1',toFrameId:'derived',type:'AFFINE',matrix:m,convention:'ROW_MAJOR_COLUMN_VECTOR',composition:'NEXT_TIMES_PREVIOUS',invertible:true,provenance:{method:'QA_INDEPENDENT_AFFINE',evidenceIds:['ev1']},validRegion:null,calibrationId:null}];Object.assign(d.objects[0],{frameId:'derived',transformIds:['qa-transform'],kind:dg.kind,drawingGeometry:dg});return d;}
const reject=(d)=>{const before=JSON.stringify(d),r=validateDrawingIR(d);assert.equal(r.ok,false,JSON.stringify(r));assert.equal(JSON.stringify(d),before);return r;};
test('independent unit scaffold is contract-only HOLD',()=>{const r=validateDrawingIR(fixture());assert.equal(r.ok,true);assert.equal(r.productGate,'HOLD');});
test('two diagonal rect corners cannot prove shear rect retention',()=>reject(derived({kind:'rect',origin:[0,0],size:[36000,36000]},[1,1,0,0,1,0,0,0,1],{kind:'rect',origin:[0,0],size:[72000,36000]})));
test('45deg rotated rect cannot falsely become axis rect from diagonal',()=>{const c=Math.SQRT1_2;reject(derived({kind:'rect',origin:[0,0],size:[36000,36000]},[c,-c,0,c,c,0,0,0,1],{kind:'rect',origin:[0,0],size:[0,36000*Math.SQRT2]}));});
test('explicit four corners for 90deg native rect preserve transform',()=>{const d=derived({kind:'rect',origin:[0,0],size:[36000,36000]},[0,-1,0,1,0,0,0,0,1],{kind:'polygon',points:[[0,0],[0,36000],[-36000,36000],[-36000,0]],closed:true});assert.equal(validateDrawingIR(d).ok,true,JSON.stringify(validateDrawingIR(d)));});
test('rotated ellipse nonuniform transform needs basis solution or rejection',()=>reject(derived({kind:'ellipse',center:[0,0],radii:[50,25],angleDeg:45},[2,0,0,0,1,0,0,0,1],{kind:'ellipse',center:[0,0],radii:[100,25],angleDeg:45})));
test('homography valid region must contain input endpoints',()=>{const g={kind:'line',start:[0,0],end:[36000,0]},d=derived(g,[1,0,0,0,1,0,0.0001,0,1],{kind:'line',start:[0,0],end:[36000/4.6,0]});Object.assign(d.transforms[0],{type:'HOMOGRAPHY',validRegion:{min:[-1,-1],max:[10000,10000]}});const r=reject(d);assert(r.errors.some(e=>e.code==='OBJECT_OUTSIDE_TRANSFORM_REGION'));});
test('duplicate IDs with equal inventory length fail closed',()=>{const d=fixture();d.sourceInventory.push(structuredClone(d.sourceInventory[0]));d.pages[0].inventoryIds.push('part1');reject(d);});
test('text part source row cannot be replaced by another retained shape',()=>{const d=fixture();const i=structuredClone(d.sourceInventory[0]);i.id='text';i.sourceBinding.partPath='/spTree/sp[1]/text';d.sourceInventory.push(i);d.pages[0].inventoryIds.push('text');d.sourceLedger.push({inventoryId:'text',disposition:'REPRESENTED',objectIds:['line1'],reason:null,nextHumanAction:null,policyEvidenceId:null});reject(d);});
test('required supported part removed only from target denominator rejected',()=>{const d=fixture();d.exportEvaluations[0].requiredInventoryIds=[];d.exportEvaluations[0].retentionLedger=[];d.exportEvaluations[0].outputEntities=[];reject(d);});
test('layout mm cannot be interpreted as REAL_WORLD solely by unit label',()=>{const d=fixture();d.frames[1].unitRole='REAL_WORLD';d.exportEvaluations[0].unitRole='REAL_WORLD';reject(d);});
test('unknown schema rejected without source mutation',()=>{const d=fixture();d.schemaVersion='unreviewed/99';reject(d);});
test('nested asymmetric group basis retains order and sign',()=>{const outer=[2,0,360000,0,3,720000,0,0,1],inner=[0,-1,240000,-1,0,210000,0,0,1],m=compose(outer,inner);assert.deepEqual(mapPoint(m,[30000,20000]),[800000,1260000]);assert.deepEqual(mapPoint(m,[90000,60000]),[720000,1080000]);});
