import {span,start,end,take} from './perf.js';
import {TrialRecorder} from './trial-recorder.js';
import {project,sample,element,pageOf,newPage,clone,uid,classes,bounds,translate} from './core.js';
import {Editor} from './commands.js';import {LocalStore} from './storage.js';import {VisionJobs} from './vision.js';
import {drawingSvg,shape,selection,hit,esc} from './render.js';import {icon} from './icons.js';
import {importFile} from './importers.js';import {exportFile,formats} from './exporters.js';import {downloadOrShare,capturePhoto} from './device.js';
import {initShell,isNative,nativeHealth} from './shell.js';
const app=document.querySelector('#app'),portal=document.querySelector('#portal'),store=new LocalStore(),vision=new VisionJobs();
let editor=null,screen='home',projects=[],selected=null,mode='select',viewMode='drawing',format='pptx',includePhoto=false,includeOriginal=false,savedRevision=-1,saveState='unsaved',panel=null,candidate=null,search='',busy=false;
let elementNodes=new Map();
let trial=null,pendingTrial=null,restoredTrialReport=null;const historyWarnings=new Set();
let gestureBusy=false;
let toastTimer,suppressBackdropUntil=0,autosaveTimer,swRegistration,installPrompt,drawKey=null,listIds=null,listOffset=0,lastOpenedId=null;
const saveError=e=>e?.name==='QuotaExceededError'?'端末の空き容量が不足しています':/別の画面/.test(e?.message||'')?'別の画面で案件が更新されています。再読込して確認してください':/整合性|保存データ|履歴/.test(e?.message||'')?'保存内容を確認できません。元データを保全し、復旧コピーを使用してください':'端末に保存できませんでした';
const toast=t=>{const n=document.querySelector('#toast');n.textContent=t;n.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.style.display='none',5500);};
const doc=()=>editor.doc,p=()=>pageOf(doc()),src=()=>doc().sources.find(s=>s.id===p().sourceId);
const btn=(a,label,i='',cls='',extra='')=>`<button type="button" data-action="${a}" class="${cls}" ${extra}>${i?icon(i):''}${label}</button>`;
const statusText=()=>saveState==='saving'?'端末に保存中':saveState==='failed'?'保存失敗・再試行が必要':savedRevision===doc()?.revision?'端末に保存済み':'未保存';
function statusHtml(){return `<span class="status ${saveState==='failed'?'failed':savedRevision===doc()?.revision?'':'unsaved'}">${statusText()}</span>`;}
function nav(active){return `<nav class="bottom-nav" aria-label="メイン">${[['home','案件','home'],['materials','素材','box'],['settings','設定','settings']].map(([a,t,i])=>btn(a,t,i,active===a?'active':'')).join('')}</nav>`;}
function thumbnail(d){const pg=pageOf(d),s=d.sources.find(s=>s.id===pg.sourceId);return s?.workImage?`<img alt="${esc(d.title)}の作業用画像" src="${s.workImage}">`:drawingSvg({...pg,elements:pg.elements.slice(0,60)});}
function home(){const tHome=start();const list=projects.filter(d=>d.title.toLowerCase().includes(search.toLowerCase())),last=projects.find(d=>d.id===lastOpenedId)||projects[0];
 app.innerHTML=`<main class="screen"><header class="home-header"><div class="row spread"><span class="brand">VDRAW<span style="color:var(--blue)">.</span></span><span class="tag">独立プロトタイプ</span></div><p class="brand-note">現場の気づきを、伝わる図面に。</p><h1>案件</h1></header><div class="searchbox">${icon('search')}<input id="search" placeholder="案件名で検索" aria-label="案件名で検索" value="${esc(search)}"></div>${btn('new','新しい図面を作る','plus','primary full')}${last?`<button class="resume" data-action="open" data-id="${last.id}">${icon('clock')}<span><strong>前回の作業を再開</strong><br><span class="small">${esc(last.title)} · ${esc(pageOf(last).name)}</span></span></button>`:''}<div class="sectionhead row spread"><h2>最近の案件</h2><span class="muted small">${list.length}件</span></div>${store.issues.length?`<div class="card stack warning"><h2>保存内容の確認が必要です</h2><p>破損した案件は上書きせず保全しました。直前の保存から別案件として復旧できます。</p>${store.issues.map(i=>btn("recover","直前保存から復旧コピーを作る","file","secondary full",`data-id="${i.id}"`)).join("")}</div>`:""}<div class="projects">${list.map(d=>`<button class="project-card" data-action="open" data-id="${d.id}"><div class="thumb">${thumbnail(d)}${d.sample?'<span class="tag">操作確認用サンプル</span>':''}</div><div class="cardbody"><h3>${esc(d.title)}</h3><p class="muted small">${d.pages.length}ページ · ${new Date(d.updatedAt).toLocaleDateString('ja-JP')}更新</p><span class="status">端末に保存済み</span> ${d.importWarnings.length?'<span class="tag">読込内容を要確認</span>':''}</div></button>`).join('')||'<div class="card empty">案件はまだありません。<br>写真か白紙から始められます。</div>'}</div><div class="sectionhead">${btn('sample','操作確認用サンプルを開く','file','secondary full')}<p class="muted small" style="margin-top:12px">サンプルは合成図形です。実写真・実AIの認識結果ではありません。</p></div></main>${nav('home')}`;
 end('home.build.dom',tHome);document.querySelector('#search').addEventListener('input',e=>{search=e.target.value;const focus=e.target.selectionStart;home();const input=document.querySelector('#search');input.focus();input.setSelectionRange(focus,focus)});
}
function edit(){const tEdit=start();gestureBusy=false;screen='edit';app.innerHTML=`<main class="editor"><header class="editor-header">${btn('back','','back','','aria-label="案件へ戻る"')}<button class="title-button" data-action="pages"><strong>${esc(doc().title)} / ${esc(p().name)}</strong>${statusHtml()}</button>${btn('save','','save','','aria-label="端末に保存"')}${btn('export','','export','','aria-label="書き出し"')}</header><div class="view-bar"><div class="segmented" aria-label="図面表示">${[['photo','元写真'],['drawing','図面'],['overlay','重ねる']].map(([a,t])=>btn('view-'+a,t,'',viewMode===a?'active':'',`aria-pressed="${viewMode===a}"`)).join('')}</div><div class="undos">${btn('undo','','undo','','aria-label="取り消し" '+(!editor.undoStack.length?'disabled':''))}${btn('redo','','redo','','aria-label="やり直し" '+(!editor.redoStack.length?'disabled':''))}</div></div><section class="canvas-wrap" aria-label="図面キャンバス"><svg id="stage" class="stage" role="application" aria-label="タップで選択、一本指で画面移動、二本指で拡大" tabindex="0"><g id="scene-group"></g></svg><span class="canvas-note">${mode==='move'?'対象移動モード':doc().sample?'操作確認用サンプル':p().calibration.status==='UNSCALED'?'未校正 · 図面座標':'対象限定の寸法'}</span><div class="canvas-bottom">${btn('pages',`${p().name} / ${doc().pages.length}`,'')}${btn('fit','全体','')}</div><span class="zoom" id="zoom-label"></span></section><nav class="editor-tools" aria-label="編集ツール">${[['select','選択','select'],['add','追加','plus'],['dimension','寸法','ruler'],['material','素材','box'],['display','表示','layers']].map(([a,t,i])=>btn(a,t,i,a===mode?'active':'')).join('')}</nav></main>`;
 end('editor.root.dom',tEdit);const stageAtRender=document.querySelector('#stage');requestAnimationFrame(()=>{if(stageAtRender!==document.querySelector('#stage'))return;draw();const tAttach=start();attachGestures();end('editor.events.register',tAttach);});
}
function geometry(){const stage=document.querySelector('#stage');if(!stage)return null;const r=stage.getBoundingClientRect(),pg=p(),fit=Math.min((r.width-32)/pg.canvas.width,(r.height-32)/pg.canvas.height),v=pg.view||{x:0,y:0,scale:1};return {r,fit,k:fit*v.scale,tx:(r.width-pg.canvas.width*fit*v.scale)/2+v.x,ty:(r.height-pg.canvas.height*fit*v.scale)/2+v.y};}
function draw(force=false){const g=geometry();if(!g)return;const n=document.querySelector('#scene-group');n.setAttribute('transform',`translate(${g.tx} ${g.ty}) scale(${g.k})`);
 const photo=(viewMode==='photo'||viewMode==='overlay')&&src()?.workImage,drawing=viewMode!=='photo';
 const key=[p().id,viewMode].join(':');if(force||key!==drawKey||!n.firstChild){drawKey=key; const tSVG=start();const svg=`<rect width="${p().canvas.width}" height="${p().canvas.height}" fill="white"/>${photo?`<image href="${esc(src().workImage)}" width="${p().canvas.width}" height="${p().canvas.height}" preserveAspectRatio="xMidYMid meet"/>`:''}<g data-drawing="objects" opacity="${viewMode==='overlay'?.75:1}">${drawing?p().elements.filter(e=>e.visible!==false).map(shape).join(''):''}</g><g data-ui-only="selection"></g>`;end('render.svg.string',tSVG);const tDOM=start();n.innerHTML=svg;end('render.svg.dom',tDOM);elementNodes=new Map();
 }const tSelection=start();const e=selected&&p().elements.find(e=>e.id===selected),ui=n.querySelector('[data-ui-only=selection]');if(ui)ui.innerHTML=drawing&&e&&e.visible!==false?selection(e):'';end('render.selection.dom',tSelection);document.querySelector('#zoom-label').textContent=Math.round(p().view.scale*100)+'%';
}
function patchShape(id){const t=start(),e=p().elements.find(e=>e.id===id),node=elementNodes.get(id)||document.querySelector('[data-drawing=objects]')?.children[p().elements.filter(e=>e.visible!==false).findIndex(e=>e.id===id)];if(e&&node&&node.isConnected&&e.visible!==false){const temp=document.createElementNS("http://www.w3.org/2000/svg","svg");temp.innerHTML=shape(e);const replacement=temp.firstElementChild;node.replaceWith(replacement);elementNodes.set(id,replacement);}else draw(true);end('render.element.dom',t);}
function restoreDrawing(before){
 const previous=pageOf(before),next=p();
 const old=previous.elements.filter(e=>e.visible!==false),now=next.elements.filter(e=>e.visible!==false);
 if(screen!=='edit'||previous.id!==next.id||JSON.stringify(previous.canvas)!==JSON.stringify(next.canvas)||old.length!==now.length||old.some((e,i)=>e.id!==now[i].id)||JSON.stringify(before.sources)!==JSON.stringify(doc().sources)){edit();return;}
 const t=start();const changed=now.filter((e,i)=>JSON.stringify(e)!==JSON.stringify(old[i]));end('render.undo.diff',t);
 if(changed.length>50)draw(true);else for(const e of changed)patchShape(e.id);
 const title=document.querySelector('.title-button strong');if(title)title.textContent=doc().title+' / '+next.name;
 const pageButton=document.querySelector('.canvas-bottom [data-action=pages]');if(pageButton)pageButton.textContent=next.name+' / '+doc().pages.length;
 draw();refreshStatus();
}
function scheduleSave(){clearTimeout(autosaveTimer);autosaveTimer=setTimeout(()=>gestureBusy?scheduleSave():save(true),700);}
function markDirty(){saveState='unsaved';refreshStatus();scheduleSave();}
function refreshStatus(){const u=document.querySelector('[data-action=undo]'),r=document.querySelector('[data-action=redo]');if(u)u.disabled=!editor.undoStack.length;if(r)r.disabled=!editor.redoStack.length;const s=document.querySelector('.editor-header .status');if(s){s.textContent=statusText();s.className='status '+(saveState==='failed'?'failed':savedRevision===doc().revision?'':'unsaved');}}
function change(label,fn){if(editor.apply(label,fn)){markDirty();}edit();}
async function save(quiet=false){if(!editor)return true;clearTimeout(autosaveTimer);const owner=editor,snapshot=owner.doc,history=owner.history(),trialOwner=trial?.projectId===owner.doc.id?trial:null;if(trialOwner)trialOwner.saving(snapshot);saveState='saving';refreshStatus();try{const r=await store.save(snapshot,history);if(trialOwner){trialOwner.saved(true);try{await store.transaction('readwrite',x=>x.put(trialOwner.report(),'vision-trial-'+snapshot.id),'meta');}catch{trialOwner.recordPersistenceError='EVIDENCE_SAVE_FAILED';}}if(editor===owner){savedRevision=r;saveState=doc().revision===r?'saved':'unsaved';if(saveState==='unsaved')scheduleSave();}refreshStatus();if(store.lastSaveInfo?.id===snapshot.id&&store.lastSaveInfo.historyOmitted&&!historyWarnings.has(snapshot.id)){historyWarnings.add(snapshot.id);toast('図面は保存済みです。Undo履歴は容量上限により再開後に保持されません');}else if(!quiet)toast('端末に保存しました');return editor!==owner||savedRevision===doc().revision;}catch(e){if(trialOwner)trialOwner.saved(false);if(editor===owner){saveState='failed';refreshStatus();}toast('保存失敗：'+saveError(e)+'。画面を閉じずにバックアップか再試行を選んでください');return false;}}
async function open(id){clearTimeout(autosaveTimer);const session=await store.loadSession(id);await store.remember(id);lastOpenedId=id;editor=new Editor(session.doc,session.history);trial=null;pendingTrial=null;restoredTrialReport=doc().adoptions.length?await store.transaction('readonly',x=>x.get('vision-trial-'+id),'meta'):null;if(restoredTrialReport)trial=TrialRecorder.restore(restoredTrialReport,doc());savedRevision=doc().revision;saveState='saved';selected=null;mode='select';viewMode=src()?.workImage?'overlay':'drawing';edit();}
function begin(d){trial=null;pendingTrial=null;restoredTrialReport=null;clearTimeout(autosaveTimer);lastOpenedId=d.id;editor=new Editor(d);savedRevision=-1;saveState='unsaved';selected=null;mode='select';viewMode=src()?.workImage?'overlay':'drawing';edit();scheduleSave();}
function sheet(title,content,actions='',kind='',modal=true){panel=kind||title;portal.innerHTML=`${modal?'<div class="panel-backdrop" data-action="dismiss"></div>':''}<section class="sheet ${kind}" role="dialog" aria-modal="${modal}" aria-label="${esc(title)}"><div class="sheet-handle"></div><header class="sheet-head"><h2>${esc(title)}</h2>${btn('dismiss','','close','','aria-label="パネルを閉じる"')}</header><div class="sheet-content">${content}</div>${actions?`<footer class="sheet-actions">${actions}</footer>`:''}</section>`;}
function dismiss(){portal.innerHTML='';panel=null;draw();}
function newSheet(){sheet('図面を始める',`<p class="muted">名前や住所の入力は、後からで大丈夫です。</p>${[['camera','カメラで撮影','camera','端末の撮影画面を開く'],['photo','写真から選択','image','権限が使えない場合もこちらへ'],['document','PDF / PowerPoint','file','原本と編集内容を分離して保存'],['blank','白紙から作成','plus','手動で図面を描く']].map(([a,t,i,n])=>`<button class="option" data-action="${a}">${icon(i)}<span><strong>${t}</strong><span class="muted">${n}</span></span></button>`).join('')}`);}
function objectSheet(id){if(trial?.projectId===doc().id&&trial.pageId===doc().activePageId&&!trial.firstEdit)trial.start('MANUAL_EDIT');selected=id;const e=p().elements.find(e=>e.id===id);if(!e)return;draw();sheet(e.name,`<div class="row spread"><span class="tag">${esc(e.category)}</span>${btn('move','対象を移動','move','secondary')}</div><label>名称<input id="object-name" value="${esc(e.name)}" maxlength="160"></label><label>分類<select id="object-class">${classes.map(c=>`<option ${c===e.category?'selected':''}>${c}</option>`).join('')}</select></label><div class="two-cols"><label>図面の実色<input id="object-color" type="color" value="${e.fill==='none'?e.stroke:e.fill}"></label><label>線の色<input id="object-stroke" type="color" value="${e.stroke}"></label></div><div class="colors">${['#BACFC7','#D8BEA0','#BFD6E4','#D5E3EF','#B88149','#394C63'].map(c=>`<button class="swatch" data-action="swatch" data-color="${c}" aria-label="実色 ${c}"><span style="background:${c}"></span></button>`).join('')}</div><label>線の太さ（図面座標）<input id="object-width" type="number" min="0" max="30" step="0.5" value="${e.strokeWidth}"></label>${e.kind==='text'?`<label>文字<input id="object-text" value="${esc(e.text)}"></label>`:''}<div class="two-cols">${btn('geometry','形・座標を修正','ruler','secondary')}${btn('hide',e.visible===false?'表示する':'非表示','eye','secondary')}${btn('forward','前面へ','layers','secondary')}${btn('backward','背面へ','layers','secondary')}${btn('delete-object','対象を削除','close','secondary danger')}</div>`,btn('apply-object','変更を確定','check','primary'), 'object',false);}
function objectList(ids=null,offset=0){listIds=ids;listOffset=offset;const es=ids?p().elements.filter(e=>ids.includes(e.id)):p().elements;sheet(ids?'重なった対象を選択':'対象一覧',`<p class="muted">細い線や非表示の対象も、一覧から選択できます。</p><p class="small muted">${es.length}件 · ${Math.min(es.length,offset+1)}〜${Math.min(es.length,offset+100)}件を表示</p><div class="two-cols">${offset>0?btn("list-prev","前の100件","","secondary"):""}${es.length>offset+100?btn("list-next","次の100件","","secondary"):""}</div><div class="objectlist">${es.slice().reverse().slice(offset,offset+100).map(e=>`<button class="objectitem" data-action="object" data-id="${e.id}"><span class="dot" style="background:${e.fill==='none'?e.stroke:e.fill}"></span><span><strong>${esc(e.name)}</strong><br><span class="muted small">${esc(e.category)}${e.visible===false?' · 非表示':''}</span></span></button>`).join('')||'<p class="empty">対象はまだありません。</p>'}</div>`);}
function geometrySheet(){const e=p().elements.find(e=>e.id===selected),b=bounds(e);sheet('形・座標を修正',`<p class="muted">座標は図面上の値です。実寸ではありません。</p><div class="vertex-preview">${drawingSvg({...p(),canvas:{width:p().canvas.width,height:p().canvas.height},elements:[e]})}</div><div class="two-cols">${['x','y','w','h'].map(k=>`<label>${{x:'横位置',y:'縦位置',w:'幅',h:'高さ'}[k]}<input id="geom-${k}" type="number" step="1" value="${b[k]}"></label>`).join('')}</div>${e.kind==='polygon'?`<h3>頂点の数値修正</h3>${e.points.map(([x,y],i)=>`<div class="two-cols"><label>頂点${i+1} X<input class="vertex-x" type="number" value="${x}"></label><label>頂点${i+1} Y<input class="vertex-y" type="number" value="${y}"></label></div>`).join('')}`:''}${btn('geometry-zoom','選択対象を拡大','search','secondary')}`,btn('apply-geometry','座標を確定','check','primary'),'geometry');}
function pagesSheet(){sheet('案件・ページ',`<label>案件名<input id="project-title" value="${esc(doc().title)}" maxlength="160"></label>${btn('rename','案件名を保存','check','secondary')}<div class="objectlist">${doc().pages.map(pg=>`<button class="objectitem" data-action="page" data-id="${pg.id}">${icon('file')}<span>${esc(pg.name)}${pg.id===p().id?' · 編集中':''}</span></button>`).join('')}</div><label>現在のページ名<input id="page-name" value="${esc(p().name)}" maxlength="100"></label>${btn('rename-page','ページ名を保存','check','secondary')}${btn('add-page','白紙ページを追加','plus','secondary')}${btn('new','資料を新しい案件に読み込む','image','secondary')}${doc().importWarnings.map(t=>`<p class="warning">${esc(t)}</p>`).join('')}`);}
function dimensionSheet(){sheet('寸法を追加',`<p class="warning">入力寸法は選んだ対象・辺だけに適用します。写真全域・奥行きの縮尺は確定しません。</p><label>表示名<input id="dimension-name" value="確認寸法"></label><label>実測した長さ（mm・任意）<input id="dimension-value" type="number" inputmode="decimal" min="1" placeholder="未入力なら未校正"></label>`,btn('add-dimension','寸法を配置','ruler','primary'));}
function displaySheet(){sheet('表示・確認',`<div class="two-cols">${btn('objects','対象一覧','layers','secondary')}${btn('fit','全体表示','eye','secondary')}</div><p class="muted">元資料はロックされています。一本指は画面移動、二本指は拡大と移動です。</p>${btn('draft','図面の下書きを作る','file','primary full')}<p class="muted">AI下書き：未接続。写真の外部送信なし・費用なし。</p>${btn('candidate-sample','候補確認の操作サンプル','file','secondary full')}<p class="small muted">合成候補です。写真認識の結果には含めません。</p>${doc().candidates.length?'<h3>保存候補</h3>'+doc().candidates.map(c=>btn('candidate-open',`${c.kind==='operation-sample'?'操作サンプル':'候補'} · ${c.status}`,'file','secondary full',`data-id="${c.id}"`)).join(''):''}`);}
function candidateSheet(){const c=candidate;sheet('候補を確認',`<span class="tag">${c.kind==='operation-sample'?'操作確認用サンプル · 実AI結果ではありません':c.kind==='protocol-fixture'?'接続手順の模擬データ · 実AI結果ではありません':'外部サービスのAI候補 · 利用者確認が必要'}</span><div class="segmented">${[['candidate-photo','元写真'],['candidate-drawing','図面'],['candidate-overlay','重ねる']].map(([a,t])=>btn(a,t,'','',`aria-label="候補 ${t}"`)).join('')}</div><div id="candidate-preview" class="export-preview">${drawingSvg({...p(),elements:c.elements},src())}</div><p class="muted">採用すると新しいページになります。現在の図面と手動修正は保持します。</p>${btn('adopt','新しいページへ採用','check','primary full')}${btn('keep-candidate','候補を保存','save','secondary full')}${btn('discard-candidate','候補を破棄','close','secondary full')}`,'','candidate');}
async function measuredExport(d,f,options){const owner=trial?.projectId===d.id&&['pptx','dxf'].includes(f)?trial:null,stage=f.toUpperCase();if(owner)owner.start(stage);try{const blob=await exportFile(d,f,options);owner?.finish(stage);if(owner)try{await store.transaction('readwrite',x=>x.put(owner.report(),'vision-trial-'+d.id),'meta');}catch{owner.recordPersistenceError='EVIDENCE_SAVE_FAILED';}return blob;}catch(e){owner?.finish(stage,'FAILED','EXPORT_FAILED');throw e;}}
function diagnostics(){const report=trial?.report()||restoredTrialReport;sheet('Vision Diagnostics',`<p>実Claude / SAM：未接続。実写真推論の成功実績はありません。</p><p>保存済み試験記録：${report?'あり':'なし'}。モデル・時刻・件数だけを記録し、写真・名称・接続先・秘密情報は含めません。</p>${report?btn('trial-download','試験記録を保存','file','secondary full'):''}${trial?`<label>見落とし対象数<input id="trial-missed" type="number" min="0" value="0"></label><label>誤分類対象数<input id="trial-misclassified" type="number" min="0" value="0"></label><label>誤形状対象数<input id="trial-shapes" type="number" min="0" value="0"></label><label><input id="trial-attest" type="checkbox">写真と候補を本人が確認しました</label>${btn('trial-assess','目視確認を記録','check','secondary full')}`:''}<p>実機、モデルload、CUDA、checkpointは未確認。模擬試験を実AI成功に数えません。</p>`,'','vision-diagnostics');}
function exportScreen(){screen='export';app.innerHTML=`<main class="screen"><div class="navline">${btn('edit','','back','','aria-label="図面へ戻る"')}<h1>書き出し</h1></div><div class="export-layout"><div class="export-preview">${drawingSvg(p(),src(),{sourceVisible:includePhoto})}<h2>${esc(doc().title)}</h2><p class="muted">${doc().pages.length}ページ · 図面座標</p><p class="warning" style="margin-top:16px">未校正の図面です。実測寸法は入力した対象に限定します。</p></div><div><p class="muted" style="margin-bottom:18px">使い方に合わせて、形式を選んでください。</p><div class="export-grid">${formats.map(f=>`<button class="format ${f.id===format?'selected':''}" data-action="format" data-format="${f.id}" aria-pressed="${f.id===format}"><span class="format-code">${f.ext}</span><span><strong>${f.title}</strong><p class="muted small">${f.note}</p></span></button>`).join('')}</div><div class="card stack" style="margin-top:18px"><label class="checklabel"><input id="include-photo" type="checkbox" ${includePhoto?'checked':''}>元写真を添付（作業用画像）</label><p class="muted small">作業用PNGを使い、位置情報などを含めません。</p>${format==='json'?`<label class="checklabel"><input id="include-original" type="checkbox" ${includeOriginal?'checked':''}>原本もバックアップに含める</label><p class="warning">原本には位置情報や顧客情報が含まれる場合があります。</p>`:''}</div><div class="export-actions">${btn('download','ファイルを作成・保存','export','primary full')}${btn('share','OSの共有画面を開く','share','secondary full')}</div><h2 style="margin:24px 0 12px">この案件の出力履歴</h2>${doc().exports.slice().reverse().map(e=>`<div class="history"><strong>${esc(e.format.toUpperCase())}</strong> · ${e.status==='downloaded'?'ファイル作成・ダウンロード開始':e.status==='share-requested'?'OS共有画面へ受渡し':'OS共有完了'}<p class="muted small">${new Date(e.at).toLocaleString('ja-JP')}</p></div>`).join('')||'<p class="muted">まだ書き出していません。</p>'}</div></div></main>`;
 document.querySelector('#include-photo').onchange=e=>{includePhoto=e.target.checked;exportScreen();};const io=document.querySelector('#include-original');if(io)io.onchange=e=>{includeOriginal=e.target.checked;};}
async function output(share){if(busy)return;busy=true;try{toast('ファイルを作成中');const snapshot=clone(doc()),blob=await measuredExport(snapshot,format,{includePhoto,includeOriginal}),name=doc().title.replace(/[\\/:*?"<>|]/g,'_')+'.'+format;
 const result=await downloadOrShare(blob,name,share);doc().exports.push({id:uid(),format,status:result,at:new Date().toISOString(),revision:doc().revision,includePhoto,includeOriginal:format==='json'&&includeOriginal});doc().revision++;markDirty();const ok=await save();exportScreen();toast(ok?'ファイルを作成し、履歴を端末に保存しました':'ファイルは作成しましたが、履歴の端末保存に失敗しました');
 }catch(e){toast(e.name==='AbortError'?'共有をキャンセルしました':'出力失敗：'+e.message);}finally{busy=false;}}
function materials(editing=false){const options=[['机','rect','家具','#D8BEA0'],['椅子','rect','家具','#BACFC7'],['植栽','ellipse','植栽','#A9C293'],['設備','rect','設備','#BFD6E4'],['車','rect','車','#D5E3EF'],['汎用図形','polygon','汎用図形','#D5E3EF']];
 const content=options.map(([name,kind,category,color])=>`<button class="option" data-action="insert-material" data-name="${name}" data-kind="${kind}" data-class="${category}" data-color="${color}">${icon('box')}<span><strong>${name}</strong><span class="muted">編集可能な汎用記号</span></span></button>`).join('');
 if(editing)sheet('素材を配置',content);else{screen='materials';app.innerHTML=`<main class="screen stack"><h1>素材</h1><p class="muted">図面編集画面から配置できます。記号は対象に合わせて修正してください。</p>${options.map(([name,kind,c,col])=>`<div class="card row">${icon('box')}<span>${name} · ${c}</span></div>`).join('')}</main>${nav('materials')}`;}}
async function settings(){if(!isNative()&&navigator.serviceWorker){try{swRegistration=await navigator.serviceWorker.getRegistration()||swRegistration;}catch{}}screen='settings';app.innerHTML=`<main class="screen stack"><h1>設定</h1><div class="card stack"><h2>保存と通信</h2><p>端末内保存のみ。同期機能は未実装です。</p><p class="muted">${navigator.onLine?'オンライン':'オフライン'} · 通信復旧によるAI自動再実行はありません。</p><p class="muted small">端末故障・アプリ削除・ブラウザのデータ消去に備え、案件バックアップを保存してください。</p></div><div class="card stack"><h2>表示</h2>${btn('large-type',document.documentElement.classList.contains('large-type')?'標準の文字サイズ':'文字を大きくする','eye','secondary')}</div><div class="card stack"><h2>接続状況</h2><p>AI下書き：未接続<br>${isNative()?"端末ブリッジ接続（実機未確認）":"Webモード"}<br>カメラ：端末のファイル撮影経路<br>OS共有：${isNative()?"端末共有入口":"ブラウザ対応時"}</p>${btn('developer','開発者向け','settings','secondary')}</div><div class="card stack"><h2>アプリと保存領域</h2><p>VDRAW MOBILE 006 · 変更後700msで自動保存</p>${btn("persist","保存領域の保持を要求","save","secondary")}${btn("storage-info","保存容量を確認","file","secondary")}${installPrompt?btn("install","ホーム画面に追加","plus","secondary"):""}${btn("check-update","更新を確認","file","secondary")}${swRegistration?.waiting?btn("apply-update","保存して更新を適用","check","primary"):""}<p class="muted small">自動保存は端末の強制終了直前には完了しない場合があります。端末保存済みの表示を確認してください。</p></div></main>${nav('settings')}`;}
const number=id=>{const n=Number(document.querySelector('#'+id).value);if(!Number.isFinite(n))throw Error('数値を入力してください');return n;};
async function action(a,target){switch(a){
 case 'home':case 'back':if(editor&&savedRevision!==doc().revision){if(!await save())return;}dismiss();selected=null;screen='home';projects=await store.list();home();break;
 case 'new':newSheet();break;case 'camera':if(isNative()){try{if(editor&&savedRevision!==doc().revision&&!await save())return;const f=await capturePhoto();if(f){dismiss();begin(await importFile(f));}}catch(e){toast('撮影を利用できません。写真から選択して続けられます');}break;}document.querySelector('#camera-input').click();break;case 'photo':case 'document':document.querySelector('#'+a+'-input').click();break;
 case 'recover':{const d=await store.recoverAsCopy(target.dataset.id);begin(d);await save();break;}
 case 'delete-object':{editor.remove(selected);markDirty();selected=null;mode='select';dismiss();edit();toast('対象を削除しました。取り消しで戻せます');break;}
 case 'blank':if(editor&&savedRevision!==doc().revision&&!await save())return;dismiss();begin(project());break;
 case 'sample':if(editor&&savedRevision!==doc().revision&&!await save())return;dismiss();begin(sample());await save();edit();break;
 case 'open':if(editor&&savedRevision!==doc().revision&&!await save())return;dismiss();await open(target.dataset.id);break;
 case 'save':await save();break;case 'edit':dismiss();edit();break;case 'export':dismiss();includePhoto=false;includeOriginal=false;exportScreen();break;
 case 'dismiss':dismiss();break;
 case 'undo':{const before=doc();dismiss();if(editor.undo()){if(trial?.projectId===doc().id)trial.actions++;selected=null;markDirty();restoreDrawing(before);}break;}
 case 'redo':{const before=doc();dismiss();if(editor.redo()){if(trial?.projectId===doc().id)trial.actions++;selected=null;markDirty();restoreDrawing(before);}break;}
 case 'view-photo':case 'view-drawing':case 'view-overlay':if(a!=='view-drawing'&&!src()?.workImage){toast('このページに元写真はありません');return;}dismiss();viewMode=a.slice(5);edit();break;
 case 'select':mode='select';selected=null;dismiss();objectList();break;
 case 'list-next':objectList(listIds,listOffset+100);break;case 'list-prev':objectList(listIds,Math.max(0,listOffset-100));break;
 case 'objects':objectList();break;case 'object':dismiss();objectSheet(target.dataset.id);break;
 case 'swatch':document.querySelector('#object-color').value=target.dataset.color;break;
 case 'apply-object':{const e=p().elements.find(e=>e.id===selected),before=clone(e),name=document.querySelector('#object-name').value,color=document.querySelector('#object-color').value,stroke=document.querySelector('#object-stroke').value,strokeWidth=number('object-width');if(strokeWidth<0||strokeWidth>30)throw Error('線幅は0〜30で入力してください');editor.update(selected,{name,category:document.querySelector('#object-class').value,fill:e.fill==='none'?'none':color,stroke:e.fill==='none'?color:stroke,strokeWidth,...(e.kind==='text'?{text:document.querySelector('#object-text').value}:{})});if(trial?.projectId===doc().id&&trial.pageId===doc().activePageId)trial.edit(before,p().elements.find(e=>e.id===selected));patchShape(selected);markDirty();dismiss();break;}
 case 'move':mode='move';dismiss();edit();toast('対象移動モード。ドラッグで選択対象を移動します');break;
 case 'hide':editor.update(selected,{visible:p().elements.find(e=>e.id===selected).visible===false});markDirty();dismiss();selected=null;edit();break;
 case 'forward':case 'backward':editor.reorder(selected,a==='forward'?1:-1);markDirty();dismiss();edit();break;
 case 'geometry':geometrySheet();break;
 case 'geometry-zoom':{const b=bounds(p().elements.find(e=>e.id===selected)),g=geometry();p().view.scale=Math.min(8,Math.min(g.r.width/(b.w+100),g.r.height/(b.h+100))/g.fit);const k=g.fit*p().view.scale;p().view.x=(p().canvas.width/2-b.x-b.w/2)*k;p().view.y=(p().canvas.height/2-b.y-b.h/2)*k;dismiss();draw();toast('拡大後は対象をタップし、数値で頂点を修正できます');break;}
 case 'apply-geometry':{const e=p().elements.find(e=>e.id===selected),before=clone(e),b=bounds(e),x=number('geom-x'),y=number('geom-y'),w=number('geom-w'),h=number('geom-h');if(w<0||h<0||w>10000||h>10000)throw Error('幅・高さは0〜10000です');
  if(e.kind==='arc'&&w!==h)throw Error('円弧は幅と高さを同じ値にしてください');const patch={x,y,w,h};if(e.kind==='polygon'){patch.points=[...document.querySelectorAll('.vertex-x')].map((n,i)=>[Number(n.value),Number(document.querySelectorAll('.vertex-y')[i].value)]);const valuesChanged=JSON.stringify(patch.points)!==JSON.stringify(e.points);if(!valuesChanged)patch.points=e.points.map(([a,bv])=>[x+(a-b.x)/(b.w||1)*w,y+(bv-b.y)/(b.h||1)*h]);}
  editor.update(selected,patch);if(trial?.projectId===doc().id&&trial.pageId===doc().activePageId)trial.edit(before,p().elements.find(e=>e.id===selected));patchShape(selected);markDirty();dismiss();break;}
 case 'add':sheet('図形を追加',`<div class="two-cols">${[['rect','四角形'],['ellipse','円・楕円'],['line','線'],['arc','円弧'],['polygon','多角形'],['text','文字']].map(([k,t])=>btn('insert',t,'plus','secondary',`data-kind="${k}"`)).join('')}</div>`);break;
 case 'insert':{const kind=target.dataset.kind,e=element(kind,{rect:'四角形',ellipse:'楕円',line:'線',arc:'円弧',polygon:'多角形',text:'文字'}[kind],kind==='line'?{fill:'none',h:0}:kind==='arc'?{fill:'none',w:160,h:160,startAngle:0,endAngle:180}:kind==='polygon'?{points:[[260,220],[500,240],[460,380],[280,365]]}:kind==='text'?{text:'新しい文字',fill:'#394C63'}:{});editor.add(e);markDirty();dismiss();viewMode='drawing';edit();requestAnimationFrame(()=>objectSheet(e.id));break;}
 case 'material':materials(true);break;
 case 'insert-material':{const e=element(target.dataset.kind,target.dataset.name,{category:target.dataset.class,fill:target.dataset.color,...(target.dataset.kind==='polygon'?{points:[[260,220],[500,240],[460,380],[280,365]]}:{})});editor.add(e);markDirty();dismiss();viewMode='drawing';edit();requestAnimationFrame(()=>objectSheet(e.id));break;}
 case 'dimension':dimensionSheet();break;case 'add-dimension':{const v=document.querySelector('#dimension-value').value,value=v?number('dimension-value'):null;if(value!==null&&value<=0)throw Error('実測寸法は正数を入力してください');const e=element('dimension',document.querySelector('#dimension-name').value,{x:300,y:650,w:400,h:0,fill:'none',text:value===null?'寸法未入力':value+' mm',dimension:{status:value===null?'UNSCALED':'MANUAL',valueMm:value,scope:'selected-edge-only',referenceElementId:selected||null,planeId:null,doesNotCalibratePage:true}});editor.add(e);markDirty();dismiss();viewMode='drawing';edit();break;}
 case 'display':displaySheet();break;case 'pages':pagesSheet();break;
 case 'page':doc().activePageId=target.dataset.id;selected=null;mode='select';viewMode='drawing';doc().revision++;markDirty();dismiss();edit();break;
 case 'add-page':change('ページの追加',d=>{const pg=newPage('図面 '+(d.pages.length+1));d.pages.push(pg);d.activePageId=pg.id;});selected=null;dismiss();break;
 case 'rename':{const value=document.querySelector('#project-title').value.trim();if(!value)throw Error('案件名を入力してください');change('案件名の変更',d=>d.title=value);dismiss();break;}
 case 'rename-page':{const value=document.querySelector('#page-name').value.trim();if(!value)throw Error('ページ名を入力してください');change('ページ名の変更',d=>pageOf(d).name=value);dismiss();break;}
 case 'fit':p().view={x:0,y:0,scale:1};doc().revision++;markDirty();dismiss();draw();break;
 case 'draft':try{await vision.draft();}catch(e){toast(e.message);}break;
 case 'candidate-sample':pendingTrial=null;candidate=vision.sampleCandidate(doc());candidateSheet();break;
 case 'candidate-open':pendingTrial=null;candidate=clone(doc().candidates.find(c=>c.id===target.dataset.id));candidateSheet();break;
 case 'candidate-photo':case 'candidate-drawing':case 'candidate-overlay':document.querySelector('#candidate-preview').innerHTML=drawingSvg({...p(),elements:candidate.elements},src(),{sourceVisible:a!=='candidate-drawing',drawingVisible:a!=='candidate-photo',overlay:a==='candidate-overlay'});break;
 case 'keep-candidate':editor.apply('候補を保存',d=>{if(!d.candidates.some(c=>c.id===candidate.id))d.candidates.push(clone(candidate));});markDirty();dismiss();edit();await save();break;
 case 'discard-candidate':if(doc().candidates.some(c=>c.id===candidate.id)){editor.apply('候補の破棄',d=>{d.candidates.find(c=>c.id===candidate.id).status='discarded';});markDirty();}candidate=null;pendingTrial=null;dismiss();edit();toast('候補を破棄しました。採用図面・手動修正は保持しています');break;
 case 'adopt':if(pendingTrial){pendingTrial.start('ADOPT');}candidate.review={status:'reviewed',method:'user-adopt-action',at:new Date().toISOString()};if(candidate.status==='discarded')throw Error('破棄した候補は採用できません');editor.apply('候補を新規ページへ採用',d=>{if(!d.candidates.some(c=>c.id===candidate.id))d.candidates.push(clone(candidate));vision.adopt(d,candidate);});if(pendingTrial){trial=pendingTrial;trial.adopted(doc());pendingTrial=null;}markDirty();selected=null;dismiss();viewMode='drawing';edit();break;
 case 'format':format=target.dataset.format;exportScreen();break;case 'download':await output(false);break;case 'share':await output(true);break;
 case 'materials':materials();break;case 'settings':settings();break;case 'large-type':document.documentElement.classList.toggle('large-type');settings();break;
 case 'persist':toast(await store.requestPersistence()?'保存領域の保持が許可されました':'保持は端末判断です。案件バックアップも保存してください');break;
 case 'storage-info':{const e=await store.estimate();toast(`使用 ${Math.round((e.usage||0)/1048576)} MB / 上限の目安 ${Math.round((e.quota||0)/1048576)} MB`);break;}
 case 'check-update':if(swRegistration){await swRegistration.update();toast(swRegistration.waiting?'更新を適用できます':'更新確認が完了しました');settings();}else toast('オフライン機能は未準備、またはNativeモードです');break;
 case 'apply-update':if(editor&&savedRevision!==doc().revision&&!await save())return;swRegistration?.waiting?.postMessage({type:'ACTIVATE_UPDATE'});break;
 case 'install':await installPrompt?.prompt();installPrompt=null;settings();break;
 case 'import-vision-result':document.querySelector('#vision-result-input').click();break;
 case 'vision-diagnostics':diagnostics();break;
 case 'trial-download':await downloadOrShare(new Blob([JSON.stringify(trial?.report()||restoredTrialReport,null,2)],{type:'application/json'}),'VDRAW-photo-trial.json');break;
 case 'trial-assess':trial.assessment({missed:number('trial-missed'),misclassified:number('trial-misclassified'),shapes:number('trial-shapes'),attested:document.querySelector('#trial-attest').checked});try{await store.transaction('readwrite',x=>x.put(trial.report(),'vision-trial-'+doc().id),'meta');}catch{trial.recordPersistenceError='EVIDENCE_SAVE_FAILED';}diagnostics();break;
 case 'developer':sheet('開発・管理の状況',`<p>Visionジョブサービス：未接続<br>Claude / SAM：実推論0件<br>認証・費用管理：非公開CLI接続準備（未接続）<br>同期：未実装<br>Native Bridge：公式プラグイン・Androidプロジェクトを用意。実機未確認<br>APK / IPA：未ビルド</p>${editor?btn("import-vision-result","Vision結果ファイルを候補確認へ","file","secondary full"):""}${btn('vision-diagnostics','Vision Diagnostics','file','secondary full')}<p>Native機能状態：${esc(JSON.stringify(nativeHealth()))}</p><p class="muted">秘密情報はこの画面に入力しません。実AIを接続する際は非公開の認証済みサービスが必要です。</p>`);break;
 }}
document.addEventListener('click',async e=>{const target=e.target.closest('[data-action]');if(!target||target.disabled)return;if(target.classList.contains('panel-backdrop')&&performance.now()<suppressBackdropUntil){e.preventDefault();return;}try{await action(target.dataset.action,target);}catch(err){toast(err.message);}});
document.querySelector('#vision-result-input').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{if(!editor)throw Error('元資料を持つ案件を開いてください');if(f.size>5*1024*1024)throw Error('Vision結果は5MB以下にしてください');const envelope=JSON.parse(await f.text());candidate=vision.receive(doc(),envelope);pendingTrial=new TrialRecorder(envelope);candidateSheet();}catch(err){toast('Vision結果の読込失敗：'+err.message);}finally{e.target.value='';}});
for(const id of ['camera','photo','document'])document.querySelector('#'+id+'-input').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{toast('資料を端末内で読み込み中');const d=await importFile(file);if(editor&&savedRevision!==doc().revision&&!await save())return;dismiss();begin(d);if(d.importWarnings.length)toast(d.importWarnings.join(' '));}catch(err){toast('読込失敗：'+err.message);}finally{e.target.value='';}});
function attachGestures(){const stage=document.querySelector('#stage'),pointers=new Map();let initial=null,dragged=false,pinch=null,moved=null;
 const local=e=>{const r=stage.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};};
 stage.addEventListener('pointerdown',e=>{if(e.button!==0)return;gestureBusy=true;e.preventDefault();const q=local(e);stage.setPointerCapture(e.pointerId);pointers.set(e.pointerId,q);
  if(pointers.size===1){initial={...q,view:clone(p().view),element:mode==='move'&&selected?clone(p().elements.find(e=>e.id===selected)):null};dragged=false;moved=null;}
  if(pointers.size===2){if(initial?.element){Object.assign(p().elements.find(e=>e.id===selected),initial.element);patchShape(selected);moved=null;}dragged=true;const [a,b]=[...pointers.values()],g=geometry(),mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2};pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),scale:p().view.scale,world:{x:(mid.x-g.tx)/g.k,y:(mid.y-g.ty)/g.k}};}
 });
 stage.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,local(e));
  if(pointers.size>=2&&pinch){const [a,b]=[...pointers.values()],mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2},g=geometry();p().view.scale=Math.max(.25,Math.min(10,pinch.scale*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,pinch.distance)));const k=g.fit*p().view.scale;p().view.x=mid.x-pinch.world.x*k-(g.r.width-p().canvas.width*k)/2;p().view.y=mid.y-pinch.world.y*k-(g.r.height-p().canvas.height*k)/2;draw();return;}
  if(!initial||pinch)return;const q=local(e),dx=q.x-initial.x,dy=q.y-initial.y;if(Math.hypot(dx,dy)>7)dragged=true;if(!dragged)return;
  if(initial.element){const g=geometry(),next=clone(initial.element);translate(next,dx/g.k,dy/g.k);Object.assign(p().elements.find(e=>e.id===selected),next);moved=next;}
  else {p().view.x=initial.view.x+dx;p().view.y=initial.view.y+dy;}if(initial.element)patchShape(selected);draw();
 });
 const finish=(e,cancel=false)=>{const q=local(e);pointers.delete(e.pointerId);if(pointers.size)return;gestureBusy=false;
  if(moved&&initial?.element){const next=clone(moved);Object.assign(p().elements.find(e=>e.id===selected),initial.element);if(!cancel){editor.update(selected,next);if(trial?.projectId===doc().id&&trial.pageId===doc().activePageId)trial.edit(initial.element,next);markDirty();}}
  if(!dragged&&!cancel&&initial&&viewMode!=='photo'){if(e.pointerType==='touch')suppressBackdropUntil=performance.now()+400;const g=geometry(),x=(q.x-g.tx)/g.k,y=(q.y-g.ty)/g.k,ids=p().elements.filter(e=>hit(e,x,y,14/g.k)).map(e=>e.id);if(ids.length>1)objectList(ids);else if(ids.length===1)objectSheet(ids[0]);else{selected=null;dismiss();}}
  if(dragged&&!cancel&&!moved){doc().revision++;markDirty();}const changed=!!moved;initial=null;pinch=null;moved=null;if(changed)patchShape(selected);draw();};stage.addEventListener('pointerup',e=>finish(e));stage.addEventListener('pointercancel',e=>finish(e,true));
 stage.addEventListener('wheel',e=>{e.preventDefault();const q=local(e),g=geometry(),wx=(q.x-g.tx)/g.k,wy=(q.y-g.ty)/g.k;p().view.scale=Math.max(.25,Math.min(10,p().view.scale*(e.deltaY<0?1.1:.9)));const k=g.fit*p().view.scale;p().view.x=q.x-wx*k-(g.r.width-p().canvas.width*k)/2;p().view.y=q.y-wy*k-(g.r.height-p().canvas.height*k)/2;draw();doc().revision++;markDirty();},{passive:false});
 stage.addEventListener('keydown',e=>{if(e.key==='Escape'){selected=null;mode='select';dismiss();}if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();action(e.shiftKey?'redo':'undo',stage);}});
}
function resize(){const vv=window.visualViewport;document.documentElement.style.setProperty('--vh',(vv?.height||window.innerHeight)+'px');if(screen==='edit')draw();}
window.addEventListener('resize',resize);window.visualViewport?.addEventListener('resize',resize);resize();
window.addEventListener('beforeunload',e=>{if(editor&&savedRevision!==doc().revision){e.preventDefault();e.returnValue='';}});
window.addEventListener('online',()=>{if(screen==='settings')settings();});window.addEventListener('offline',()=>{if(screen==='settings')settings();toast('オフラインです。編集と端末保存は続けられます');});
// Diagnostic access for tests; never calls AI or mutates existing application storage.
window.VDRAW={get trial(){return trial?.report()||restoredTrialReport},profile:take,store,vision,get editor(){return editor},get state(){return {screen,selected,mode,viewMode,savedRevision,saveState}},save,begin,exportFile,importFile,draw,action,back:handleBack};
app.innerHTML='<main class="screen stack" aria-busy="true"><h1>案件を読み込み中</h1><p>端末の保存内容を確認しています。</p></main>';
try{projects=await store.list();lastOpenedId=await store.lastProject();home();}catch(e){app.innerHTML=`<main class="screen stack"><h1>端末保存を開始できません</h1><p class="warning">${esc(e.message)}</p>${btn('blank','白紙で作業を始める','plus','primary')}<p>バックアップへの書き出しで作業を保全してください。</p></main>`;}
async function handleBack(){if(panel){dismiss();return true;}if(screen==='export'){edit();return true;}if(screen!=='home'){await action('back',{});return true;}return false;}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&editor&&savedRevision!==doc().revision)save(true);});
window.addEventListener('pagehide',()=>{if(editor&&savedRevision!==doc().revision)save(true);});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;if(screen==='settings')settings();});
await initShell({back:handleBack,suspend:()=>save(true),resume:()=>{resize();refreshStatus();},restoredPhoto:async f=>{if(editor&&savedRevision!==doc().revision&&!await save())return;begin(await importFile(f));},error:()=>toast('端末機能の一部を利用できません。写真選択・端末保存で続けられます')});
if(!isNative()&&'serviceWorker'in navigator){let refreshing=false;const hadController=!!navigator.serviceWorker.controller;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(refreshing||!hadController)return;refreshing=true;location.reload();});navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(r=>{swRegistration=r;r.addEventListener('updatefound',()=>{r.installing?.addEventListener('statechange',()=>{if(r.waiting&&navigator.serviceWorker.controller){toast('画面の更新があります。設定から保存して適用できます');if(screen==='settings')settings();}});});}).catch(()=>toast('オフライン用画面の準備に失敗しました。端末保存とは別の状態です'));}

