"""Independent deterministic synthetic source witness; not B output or external app."""
import zipfile,json,hashlib
from pathlib import Path
R=Path(__file__).resolve().parents[1];P='http://schemas.openxmlformats.org/presentationml/2006/main';A='http://schemas.openxmlformats.org/drawingml/2006/main';REL='http://schemas.openxmlformats.org/officeDocument/2006/relationships'
def rgb(v,a):return f'<a:solidFill><a:srgbClr val="{v}"><a:alpha val="{a}"/></a:srgbClr></a:solidFill>'
def sp(i,g,paint):return f'<p:sp><p:nvSpPr><p:cNvPr id="{i}" name="property-witness-{i}"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="-36000" y="72000"/><a:ext cx="72000" cy="36000"/></a:xfrm><a:prstGeom prst="{g}"><a:avLst/></a:prstGeom>{paint}</p:spPr></p:sp>'
body=sp(2,'line','<a:noFill/><a:ln w="3600">'+rgb('010203','50000')+'<a:prstDash val="solid"/></a:ln>')+sp(3,'rect',rgb('AABBCC','100000')+'<a:ln><a:noFill/></a:ln>')+sp(4,'rect',rgb('445566','80000')+'<a:ln w="7200">'+rgb('778899','50000')+'<a:prstDash val="solid"/></a:ln>')
parts={'[Content_Types].xml':'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="xml" ContentType="application/xml"/><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/></Types>','_rels/.rels':f'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="r0" Type="{REL}/officeDocument" Target="ppt/presentation.xml"/></Relationships>','ppt/presentation.xml':f'<p:presentation xmlns:p="{P}" xmlns:r="{REL}"><p:sldIdLst><p:sldId id="256" r:id="r1"/></p:sldIdLst><p:sldSz cx="7200000" cy="5400000"/></p:presentation>','ppt/_rels/presentation.xml.rels':f'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="r1" Type="{REL}/slide" Target="slides/slide1.xml"/></Relationships>','ppt/slides/slide1.xml':f'<p:sld xmlns:p="{P}" xmlns:a="{A}" xmlns:r="{REL}"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name="root"/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/>{body}</p:spTree></p:cSld></p:sld>'}
with zipfile.ZipFile(R/'fixtures/synthetic-g04-property-witness.pptx','w',compression=zipfile.ZIP_DEFLATED) as z:
 for n,s in sorted(parts.items()):i=zipfile.ZipInfo(n,date_time=(2026,10,7,0,0,0));i.compress_type=zipfile.ZIP_DEFLATED;z.writestr(i,s)
truth={'classification':'SYNTHETIC_NOT_EXTERNAL_APP','sourceObjectCount':3,'sourceComponentCount':3,'object2':{'strokeRaw':'010203','stroke':'#010203','fillRaw':'noFill','fill':None,'widthRaw':'3600','widthEMU':3600,'alphaRaw':'50000','opacity':0.5,'dashRaw':'solid','dashExpected':'UNRESOLVED_UNTIL_NATIVE_ENCODING_ADOPTED','endpointsCADmm':[[-1,148],[1,147]]},'object3':{'strokeRaw':'noFill','stroke':None,'fillRaw':'AABBCC','fill':'#AABBCC','alphaRaw':'100000','opacity':1,'widthDashApplicability':'NOT_APPLICABLE_EXPLICIT_NOFILL_STROKE'},'object4':{'widthRaw':'7200','widthEMU':7200,'strokeRaw':'778899','fillRaw':'445566','paintAlphasRaw':['50000','80000'],'singleOpacityExpected':'UNRESOLVED_PER_PAINT_OPACITY_UNREPRESENTABLE'},'productGate':'HOLD'}
(R/'fixtures/synthetic-g04-design-truth.json').write_text(json.dumps(truth,indent=2)+'\n');print('synthetic witness3objects generated')
