/** New G focused fixed-writer guard/determinism checks; no existing producer suite rerun. */
import fs from'node:fs/promises';import path from'node:path';import{pathToFileURL}from'node:url';import{webcrypto}from'node:crypto';
const droot=process.env.VDRAW_DXF_FIXED_ROOT,b=path.join(droot,'docs/architecture/tracks/B/mm-dxf-evidence');const{drawingIRToReviewDXF}=await import(pathToFileURL(path.join(droot,'routes/dxf/mm-geometry-review.mjs')));const{validateDrawingIR}=await import(pathToFileURL(process.env.VDRAW_A2_VALIDATOR));const checks=[];
for(const n of ['native-vdraw-n01','generic-synthetic-g01','generic-synthetic-g02-nested','synthetic-g03-expanded','explicit-paint-width-alpha-witness','synthetic-g04-property-witness']){const ir=JSON.parse(await fs.readFile(path.join(b,n+'.evaluated-ir.json'),'utf8')),v=validateDrawingIR(ir);checks.push({name:n+'-evaluated-IR',scope:'FIXED_SAVED_IR_CONTRACT_ONLY',status:v.ok?'PASS':'FAIL',errors:v.errors});}
const input=JSON.parse(await fs.readFile(new URL('../../b2-review/evidence/synthetic-g04-property-witness.adapter-result.json',import.meta.url),'utf8'));
async function reject(name,mut,options,code){const a=structuredClone(input);mut(a);let actual='NOT_REJECTED';try{await drawingIRToReviewDXF(a,{crypto:webcrypto,...options});}catch(e){actual=e.code??e.message;}checks.push({name,expectedCode:code,actualCode:actual,status:actual===code?'PASS':'FAIL',scope:'NEW_FOCUSED_WRITER_INPUT_ADVERSE'});}
await reject('input-request-fake-FULL',()=>{},{requestedReadiness:'FULL'},'REVIEW_FULL_OR_PRODUCT_READINESS_FORBIDDEN');
await reject('input-product-promoted',a=>{a.productGate='PASS';},{},'INPUT_GATE_PROMOTION_FORBIDDEN');
await reject('input-real-world-scale-forgery',a=>{a.document.scaleStatus='CALIBRATED';},{},'REAL_WORLD_OR_CALIBRATION_OUT_OF_SCOPE');
await reject('input-nonfinite-coordinate',a=>{a.document.objects[0].drawingGeometry.start[0]=NaN;},{},'UNSAFE_OUTPUT_COORDINATE');
await reject('input-unreviewed-transform-scope',a=>{a.document.transforms[0].provenance.method='UNREVIEWED';},{},'UNREVIEWED_TRANSFORM_SCOPE');
await reject('input-source-hash-forgery',a=>{a.manifest.sourceHash='0'.repeat(64);},{},'SOURCE_HASH_BINDING_MISMATCH');
const before=JSON.stringify(input),one=await drawingIRToReviewDXF(input,{crypto:webcrypto}),two=await drawingIRToReviewDXF(structuredClone(input),{crypto:webcrypto});checks.push({name:'new-G04-focused-determinism-no-source-mutation',scope:'NEW_G_REVIEW_GUARD_ONLY',status:JSON.stringify(one)===JSON.stringify(two)&&JSON.stringify(input)===before?'PASS':'FAIL'});let exact=true;for(const f of one.artifacts)exact&&=f.text===await fs.readFile(path.join(b,f.filename),'utf8');checks.push({name:'new-G04-deterministic-output-matches-fixed-bytes',scope:'NEW_G_REVIEW_GUARD_ONLY',status:exact?'PASS':'FAIL'});
const r={schema:'vdraw-G-fixed-B377-contract-determinism-checks/1',fixedWriterHEAD:'377afdc9c34e60a01a6cb0aebf33099875c9470c',IRDocumentsValidated:6,newNamedTests:8,oldSuitesRerun:false,checks,pass:checks.filter(x=>x.status==='PASS').length,fail:checks.filter(x=>x.status==='FAIL').length,appearanceFindingScopeSeparate:true,productGate:'HOLD',actualJw:'NOT_RUN'};await fs.writeFile(new URL('../evidence/B377-independent-contract-determinism-checks.json',import.meta.url),JSON.stringify(r,null,2)+'\n');console.log(JSON.stringify({pass:r.pass,fail:r.fail}));if(r.fail)process.exitCode=1;
